(defun diogenes-completing-author-greek ()
  "Reads the name of a Greek author from the minibuffer and returns the corresponding TLG number"
(substring (completing-read "Author: " '(""
			      "Apollonius Rhodius Epic. (0001)"
			      "Theognis Eleg. (0002)"
			      "Thucydides Hist. (0003)"
			      "Diogenes Laertius Biogr. (0004)"
			      "Theocritus Bucol. (0005)"
			      "Euripides Trag. (0006)"
			      "Plutarchus Biogr. et Phil. (0007)"
			      "Athenaeus Soph. (0008)"
			      "Sappho Lyr. (0009)"
			      "Isocrates Orat. (0010)"
			      "Sophocles Trag. (0011)"
			      "Homerus Epic. Homer (0012)"
			      "Hymni Homerici Homeric Hymns (0013)"
			      "Demosthenes Orat. (0014)"
			      "Herodianus Hist. (0015)"
			      "Herodotus Hist. (0016)"
			      "Isaeus Orat. (0017)"
			      "Philo Judaeus Phil. (0018)"
			      "Aristophanes Comic. (0019)"
			      "Hesiodus Epic. (0020)"
			      "Nicander Epic. (0022)"
			      "Oppianus Epic. (0023)"
			      "Oppianus Epic. (0024)"
			      "Aeschines Orat. (0026)"
			      "Andocides Orat. (0027)"
			      "Antiphon Orat. (0028)"
			      "Dinarchus Orat. (0029)"
			      "Hyperides Orat. (0030)"
			      "Novum Testamentum New Testament (0031)"
			      "Xenophon Hist. (0032)"
			      "Pindarus Lyr. (0033)"
			      "Lycurgus Orat. (0034)"
			      "Moschus Bucol. (0035)"
			      "Bion Bucol. (0036)"
			      "Anacharsidis Epistulae (0037)"
			      "Arcesilai Epistula (0038)"
			      "Mithridatis Epistula (0039)"
			      "Calani Epistula (0040)"
			      "Chionis Epistulae (0041)"
			      "Alexandri Magni Epistulae (0042)"
			      "Amasis Epistulae (0043)"
			      "Antiochi Regis Epistulae (0044)"
			      "Artaxerxis Epistulae (0045)"
			      "Niciae Epistula (0046)"
			      "Pausaniae I Et Xerxis Epistulae (0047)"
			      "Philippus II Rex Macedonum <Epist.> (0048)"
			      "Pisistrati Epistula (0049)"
			      "Ptolemaei II Philadelphi Et Eleazari Epistulae (0050)"
			      "<Melissa> Phil. (0051)"
			      "Menippus Phil. (0052)"
			      "Phalaridis Epistulae (0053)"
			      "<Theano> Phil. (0054)"
			      "Themistoclis Epistulae (0055)"
			      "Thrasybuli Epistula (0056)"
			      "Galenus Med. (0057)"
			      "Aeneas Tact. (0058)"
			      "Plato Phil. (0059)"
			      "Diodorus Siculus Hist. (0060)"
			      "Pseudo-Lucianus Soph. (0061)"
			      "Lucianus Soph. (0062)"
			      "Dionysius Thrax Gramm. (0063)"
			      "Periplus Hannonis (0064)"
			      "Scylax Perieg. (0065)"
			      "Dicaearchus Phil. (0066)"
			      "Agatharchides Geogr. (0067)"
			      "Pseudo-Scymnus Geogr. (0068)"
			      "Dionysius Geogr. (0069)"
			      "Periplus Maris Erythraei (0071)"
			      "Anonymi Grammatici Gramm. (0072)"
			      "Flavius Arrianus Hist. et Phil. (0074)"
			      "Periplus Ponti Euxini (0075)"
			      "Periplus Maris Magni (0077)"
			      "Menippus Geogr. (0079)"
			      "Dionysius Halicarnassensis Hist. et Rhet. (0081)"
			      "Apollonius Dyscolus Gramm. (0082)"
			      "Dionysius Geogr. (0083)"
			      "Dionysius Perieg. (0084)"
			      "Aeschylus Trag. (0085)"
			      "Aristoteles Phil. et Corpus Aristotelicum Aristotle (0086)"
			      "Aelius Herodianus et Pseudo-Herodianus Gramm. et Rhet. (0087)"
			      "Aristoxenus Mus. (0088)"
			      "Praxiphanes Phil. (0089)"
			      "Agathemerus Geogr. (0090)"
			      "Anonymi Geographiae Expositio Compendiaria (0092)"
			      "Theophrastus Phil. (0093)"
			      "Pseudo-Plutarchus (0094)"
			      "Hermodorus Phil. (0095)"
			      "Aesopus Scr. Fab. et Aesopica (0096)"
			      "Diogenianus Gramm. (0097)"
			      "Zenobius Sophista <Paroemiogr.> (0098)"
			      "Strabo Geogr. (0099)"
			      "Abydenus Hist. (0116)"
			      "Zenonis Epistula (0125)"
			      "Aulus Licinius Archias Epigr. (0127)"
			      "Archimelus Epigr. (0131)"
			      "Asclepiades Epigr. (0137)"
			      "Athenaeus Epigr. (0141)"
			      "Boethus Epigr. (0146)"
			      "Diodorus Rhet. (0165)"
			      "Diotimus Epic. (0174)"
			      "Marcus Cornelius Fronto Rhet. (0186)"
			      "Hedyle Epigr. (0197)"
			      "Hedylus Epigr. (0198)"
			      "Bacchylides Lyr. (0199)"
			      "Mantissa Proverbiorum (0200)"
			      "Isyllus Lyr. (0201)"
			      "Mace(donius) Lyr. (0202)"
			      "Limenius Lyr. (0203)"
			      "Aristonous Lyr. (0204)"
			      "Philodamus Lyr. (0205)"
			      "Theocles Lyr. (0206)"
			      "Hermocles Lyr. (0207)"
			      "Dosiadas Lyr. (0208)"
			      "Seleucus Lyr. (0209)"
			      "Euphronius Lyr. (0210)"
			      "Simias Gramm. (0211)"
			      "Philetas Eleg. et Gramm. (0212)"
			      "Hermesianax Eleg. (0213)"
			      "Phanocles Eleg. (0214)"
			      "Antagoras Epic. (0215)"
			      "Alexander Lyr. et Trag. (0216)"
			      "Anacreon Junior Eleg. (0217)"
			      "Nicaenetus Epic. (0218)"
			      "Rhianus Epic. (0219)"
			      "Moero Epic. (0220)"
			      "Euphorion Epic. (0221)"
			      "Eratosthenes et Eratosthenica Philol. (0222)"
			      "Anonymi Curetum Hymnus (0227)"
			      "Anonymi Hymnus In Dactylos Idaeos (0228)"
			      "Lyrica Adespota (CA) (0230)"
			      "Elegiaca Adespota (CA) (0231)"
			      "Archilochus Eleg. et Iamb. (0232)"
			      "Hipponax Iamb. (0233)"
			      "Elegiaca Adespota (IEG) (0234)"
			      "Iambica Adespota (IEG) (0235)"
			      "Alcibiades <Eleg.> (0236)"
			      "Anacreon Lyr. (0237)"
			      "Ananius Iamb. (0238)"
			      "Antimachus Eleg. et Epic. (0239)"
			      "Hermolochus Lyr. (0240)"
			      "Aristoxenus <Comic.> (0241)"
			      "Asius Eleg. et Epic. (0242)"
			      "Callinus Eleg. (0243)"
			      "Cleobulina Scriptor Aenigmatum (0244)"
			      "Demodocus Eleg. (0245)"
			      "Dionysius Chalcus Eleg. (0246)"
			      "Dionysius II <Eleg.> (0247)"
			      "Diphilus Epic. et Iamb. (0248)"
			      "Echembrotus Eleg. et Lyr. (0249)"
			      "Euclides Comic. vel Iamb. (0250)"
			      "Euenus Eleg. (0251)"
			      "Hermippus Comic. (0252)"
			      "[Homerus] <Epic.> (0253)"
			      "Melanthius Eleg. et Trag. (0254)"
			      "Mimnermus Eleg. (0255)"
			      "Panarces Scriptor Aenigmatum (0256)"
			      "Philiscus Rhet. (0257)"
			      "Pigres Eleg. (0258)"
			      "Scythinus Poet. Phil. (0259)"
			      "Semonides Eleg. et Iamb. (0260)"
			      "Simonides Lyr. (0261)"
			      "Socrates Phil. (0262)"
			      "Solon Nomographus et Poeta (0263)"
			      "Susarion Comic. (0264)"
			      "Timocreon Lyr. (0265)"
			      "Tyrtaeus Eleg. (0266)"
			      "Xenophanes Poet. Phil. (0267)"
			      "Mesomedes Lyr. (0268)"
			      "Nautarum Cantiunculae (0269)"
			      "Conventus Avium (0271)"
			      "De Arboribus Avibusque Fabulae (0272)"
			      "Scolia Alphabetica (0273)"
			      "Peirazomene (0275)"
			      "Cantus Lugubris (0276)"
			      "Monodia (0277)"
			      "Praelusio Mimi (0278)"
			      "Discipulorum Cantiuncula (0279)"
			      "Andromachus Poet. Med. (0280)"
			      "Marcellus Poet. Med. (0281)"
			      "Anonymus De Viribus Herbarum (0282)"
			      "Heraclides Ponticus Junior Gramm. (0283)"
			      "Aelius Aristides Rhet. (0284)"
			      "Carmen Astrologicum (0286)"
			      "Pisander Epic. (0288)"
			      "Ammonius Epigr. (0289)"
			      "Encomium Ducis Thebaidos (0290)"
			      "Alcman Lyr. (0291)"
			      "Stesichorus Lyr. (0292)"
			      "Ibycus Lyr. (0293)"
			      "Corinna Lyr. (0294)"
			      "Carmina Popularia (PMG) (0295)"
			      "Carmina Convivialia (PMG) (0296)"
			      "Lyrica Adespota (PMG) (0297)"
			      "Eumelus Epic. (0298)"
			      "Terpander Lyr. (0299)"
			      "Acta Alexandrinorum (0300)"
			      "Thespis Trag. (0301)"
			      "Choerilus Trag. (0302)"
			      "Phrynichus Trag. (0303)"
			      "Acta Et Martyrium Apollonii (0304)"
			      "Aristias Trag. (0305)"
			      "Aristarchus Trag. (0306)"
			      "Neophron Trag. (0307)"
			      "Ion Phil. et Poeta (0308)"
			      "Achaeus Trag. (0309)"
			      "Carcinus Trag. (0310)"
			      "Iophon Trag. (0311)"
			      "Philocles Trag. (0312)"
			      "Theognis Trag. (0313)"
			      "Morsimus Trag. (0314)"
			      "Sthenelus Trag. (0315)"
			      "Xenocles Trag. (0316)"
			      "Acta Joannis (0317)"
			      "Agathon Trag. (0318)"
			      "Critias Eleg., Phil. et Trag. (0319)"
			      "Diogenes Trag. (0320)"
			      "Aeschylus Trag. (0321)"
			      "Dicaeogenes Trag. (0322)"
			      "Antiphon Trag. (0323)"
			      "Patrocles Trag. (0324)"
			      "Astydamas Trag. (0325)"
			      "Sophocles Junior Trag. (0326)"
			      "Carcinus Junior Trag. (0327)"
			      "Chaeremon Trag. (0328)"
			      "Theodectas Trag. (0329)"
			      "Dionysius I <Trag.> (0330)"
			      "<Polyidus> Trag. (0331)"
			      "Cleaenetus Trag. (0332)"
			      "Timocles Trag. (0333)"
			      "Diogenes Phil. et Trag. (0334)"
			      "Philiscus Trag. (0335)"
			      "Crates Poet. Phil. (0336)"
			      "Python Trag. (0337)"
			      "Sosiphanes Trag. (0338)"
			      "Moschion Trag. (0339)"
			      "Sositheus Trag. (0340)"
			      "Lycophron Trag. (0341)"
			      "Nicomachus Trag. (0342)"
			      "Ezechiel Trag. (0343)"
			      "Melanthius Trag. (0344)"
			      "Apollonides Trag. (0345)"
			      "Pompeius Macer <Trag.> (0346)"
			      "Serapion Trag. (0347)"
			      "Biotus Trag. (0348)"
			      "Demonax <Trag.> (0349)"
			      "<Dionysius Scymnaeus> Trag. vel Comic. (0350)"
			      "[Hippothoon] Trag. (0351)"
			      "Isidorus Trag. (0352)"
			      "<Sclerias> Trag. (0353)"
			      "Zenodotus Trag. (0354)"
			      "Zopyrus Trag. (0355)"
			      "Didymus Scriptor De Mensuris (0357)"
			      "Nicomachus Math. (0358)"
			      "Isidorus Scriptor Hymnorum (0359)"
			      "Armenidas Hist. (0360)"
			      "Cleonides Mus. (0361)"
			      "Claudius Ptolemaeus Math. (0363)"
			      "Danaïs vel Danaïdes (0364)"
			      "Apollodorus Lyr. (0365)"
			      "Lasus Lyr. (0366)"
			      "Tynnichus Lyr. (0367)"
			      "Cydias Lyr. (0368)"
			      "Telesilla Lyr. (0369)"
			      "Lamprocles Lyr. (0370)"
			      "Diagoras Lyr. (0371)"
			      "Praxilla Lyr. (0372)"
			      "Melanippides Lyr. (0373)"
			      "Licymnius Lyr. (0374)"
			      "Cinesias Lyr. (0375)"
			      "Timotheus Lyr. (0376)"
			      "Telestes Lyr. (0377)"
			      "Ariphron Lyr. (0378)"
			      "Philoxenus Lyr. (0379)"
			      "Philoxenus Lyr. (0380)"
			      "Lycophronides Lyr. (0381)"
			      "Castorion Lyr. (0382)"
			      "Alcaeus Lyr. (0383)"
			      "Acta Justini Et Septem Sodalium (0384)"
			      "Cassius Dio Hist. Dio Cassius (0385)"
			      "Chilonis Epistula (0386)"
			      "Sapphus vel Alcaei Fragmenta (0387)"
			      "Acta Pauli (0388)"
			      "Acta Petri (0389)"
			      "Martyrium Carpi, Papyli Et Agathonicae (0390)"
			      "Acta Scillitanorum Martyrum (0391)"
			      "Acusilaus Hist. (0392)"
			      "Apollonius Comic. (0394)"
			      "Diophantus Comic. (0395)"
			      "Euphanes Comic. (0396)"
			      "Pronomus Lyr. (0397)"
			      "Simylus Comic. (0398)"
			      "Eudoxus Comic. (0399)"
			      "Alcaeus Comic. (0400)"
			      "Alexander Comic. (0401)"
			      "Alexis Comic. (0402)"
			      "Amipsias Comic. (0403)"
			      "Amphis Comic. (0404)"
			      "Anaxandrides Comic. (0405)"
			      "Anaxilas Comic. (0406)"
			      "Anaxippus Comic. (0407)"
			      "Comica Adespota (CAF) (0408)"
			      "Antidotus Comic. (0409)"
			      "Antiphanes Comic. (0410)"
			      "Apollodorus Comic. (0411)"
			      "Apollodorus Carystius vel Apollodorus Gelous Comic. (0412)"
			      "Apollodorus Comic. (0413)"
			      "Apollophanes Comic. (0414)"
			      "Araros Comic. (0415)"
			      "Archedicus Comic. (0416)"
			      "Archippus Comic. (0417)"
			      "Aristagoras Comic. (0418)"
			      "Aristomenes Comic. (0419)"
			      "Aristonymus Comic. (0420)"
			      "Aristophon Comic. (0421)"
			      "Athenio Comic. (0422)"
			      "Autocrates Comic. (0423)"
			      "Axionicus Comic. (0424)"
			      "Bato Comic. (0425)"
			      "Callias Comic. (0426)"
			      "<Callippus> Comic. (0427)"
			      "Cantharus Comic. (0428)"
			      "Cephisodorus Comic. (0429)"
			      "Chariclides Comic. (0430)"
			      "Chionides Comic. (0431)"
			      "Clearchus Comic. (0432)"
			      "Crates Comic. (0433)"
			      "Cratinus Comic. (0434)"
			      "Cratinus Junior Comic. (0435)"
			      "Crito Comic. (0436)"
			      "Crobylus Comic. (0437)"
			      "Damoxenus Comic. (0438)"
			      "Demetrius Comic. (0439)"
			      "Demetrius Junior Comic. (0440)"
			      "Demonicus Comic. (0441)"
			      "Dexicrates Comic. (0442)"
			      "Diocles Comic. (0443)"
			      "Diodorus Comic. (0444)"
			      "Dionysius Comic. (0445)"
			      "Dioxippus Comic. (0446)"
			      "Diphilus Comic. (0447)"
			      "Dromo Comic. (0448)"
			      "Ecphantides Comic. (0449)"
			      "Ephippus Comic. (0450)"
			      "Epicrates Comic. (0451)"
			      "Epigenes Comic. (0452)"
			      "Epilycus Comic. (0453)"
			      "Epinicus Comic. (0454)"
			      "Eriphus Comic. (0455)"
			      "Euangelus Comic. (0456)"
			      "Eubulides Comic. (0457)"
			      "Eubulus Comic. (0458)"
			      "Eunicus Comic. (0459)"
			      "Euphro Comic. (0460)"
			      "Eupolis Comic. (0461)"
			      "Euthycles Comic. (0462)"
			      "Hegemon Parodius (0463)"
			      "Hegesippus Comic. (0464)"
			      "Heniochus Comic. (0465)"
			      "Heraclides Comic. (0466)"
			      "Timotheus Trag. (0467)"
			      "Hipparchus Comic. (0468)"
			      "Laon Comic. (0469)"
			      "Leuco Comic. (0470)"
			      "Lynceus Comic. (0471)"
			      "Lysippus Comic. (0472)"
			      "Machon Comic. (0473)"
			      "Magnes Comic. (0474)"
			      "Metagenes Comic. (0475)"
			      "Mnesimachus Comic. (0476)"
			      "Myrtilus Comic. (0477)"
			      "Nausicrates Comic. (0478)"
			      "Nico Comic. (0479)"
			      "Nicochares Comic. (0480)"
			      "Nicolaus Comic. (0481)"
			      "Nicomachus Comic. (0482)"
			      "Nicophon Comic. (0483)"
			      "Nicostratus Comic. (0484)"
			      "Ophelio Comic. (0485)"
			      "Pherecrates Comic. (0486)"
			      "Philemon Comic. (0487)"
			      "Philemon Junior Comic. (0488)"
			      "Philetaerus Comic. (0489)"
			      "Philippides Comic. (0490)"
			      "Philiscus Comic. (0491)"
			      "Philonides Comic. (0492)"
			      "Philostephanus Comic. (0493)"
			      "Philyllius Comic. (0494)"
			      "Phoenicides Comic. (0495)"
			      "Phrynichus Comic. (0496)"
			      "Plato Comic. (0497)"
			      "Poliochus Comic. (0498)"
			      "Polyzelus Comic. (0499)"
			      "Posidippus Comic. (0500)"
			      "Sannyrion Comic. (0501)"
			      "Sophilus Comic. (0502)"
			      "Sosicrates Comic. (0503)"
			      "Sosipater Comic. (0504)"
			      "Sotades Comic. (0505)"
			      "Stephanus Comic. (0506)"
			      "Straton Comic. (0507)"
			      "Strattis Comic. (0508)"
			      "<Myia> Phil. (0509)"
			      "Teleclides Comic. (0510)"
			      "Theognetus Comic. (0511)"
			      "Theophilus Comic. (0512)"
			      "Theopompus Comic. (0513)"
			      "Thugenides Comic. (0514)"
			      "Timocles Comic. (0515)"
			      "Timostratus Comic. (0516)"
			      "Timotheus Comic. (0517)"
			      "Xenarchus Comic. (0518)"
			      "Xeno Comic. (0519)"
			      "Arcesilaus Comic. (0520)"
			      "Epicharmus Comic. et Pseudepicharmea (0521)"
			      "Pisander Epic. (0522)"
			      "Menecrates Comic. (0523)"
			      "Sophron Mimogr. (0524)"
			      "Pausanias Perieg. (0525)"
			      "Flavius Josephus Hist. (0526)"
			      "Septuaginta (0527)"
			      "Aëtius Doxogr. (0528)"
			      "Arius Didymus Doxogr. (0529)"
			      "Pseudo-Galenus Med. (0530)"
			      "Hermias Apol. (0531)"
			      "Achilles Tatius Scr. Erot. (0532)"
			      "Callimachus Philol. (0533)"
			      "Callisthenes Hist. (0534)"
			      "Demades Orat. et Rhet. (0535)"
			      "Ephorus Hist. (0536)"
			      "Epicurus Phil. (0537)"
			      "Hecataeus Hist. (0538)"
			      "Hellanicus Hist. (0539)"
			      "Lysias Orat. (0540)"
			      "Menander Comic. (0541)"
			      "Julius Pollux Gramm. (0542)"
			      "Polybius Hist. (0543)"
			      "Sextus Empiricus Phil. (0544)"
			      "Claudius Aelianus Soph. (0545)"
			      "Aelianus Tact. (0546)"
			      "Anaximenes Hist. et Rhet. (0547)"
			      "Pseudo-Apollodorus Myth. (0548)"
			      "Apollodorus Gramm. (0549)"
			      "Apollonius Geom. (0550)"
			      "Appianus Hist. (0551)"
			      "Archimedes Geom. (0552)"
			      "Artemidorus Onir. (0553)"
			      "Chariton Scr. Erot. (0554)"
			      "Clemens Alexandrinus Theol. (0555)"
			      "Asclepiodotus Tact. (0556)"
			      "Epictetus Phil. (0557)"
			      "Hellenica (0558)"
			      "Heron Mech. (0559)"
			      "[Longinus] Rhet. Pseudo-Longinus (0560)"
			      "Longus Scr. Erot. (0561)"
			      "Marcus Aurelius Antoninus Imperator Phil. (0562)"
			      "Maximus Soph. (0563)"
			      "Rufus Med. (0564)"
			      "Soranus Med. (0565)"
			      "Theopompus Hist. (0566)"
			      "Antigonus Paradox. (0568)"
			      "Apollonius Paradox. (0569)"
			      "Archelaus Paradox. (0570)"
			      "Aristocles Paradox. (0571)"
			      "Gaius Scr. Eccl. (0572)"
			      "Lysimachus Hist. (0574)"
			      "Musaeus Epic. (0576)"
			      "Nicolaus Hist. (0577)"
			      "Nymphodorus Hist. (0578)"
			      "Orphica (0579)"
			      "Paradoxographus Florentinus (0580)"
			      "Paradoxographus Palatinus (0581)"
			      "Paradoxographus Vaticanus (0582)"
			      "Philochorus Hist. (0583)"
			      "Philostephanus Hist. (0584)"
			      "Publius Aelius Phlegon Paradox. (0585)"
			      "Polemon Perieg. (0586)"
			      "Sotion <Paradox.> (0587)"
			      "Antisthenes Phil. et Rhet. (0591)"
			      "Hermogenes Rhet. (0592)"
			      "Gorgias Rhet. et Soph. (0593)"
			      "Alexander Rhet. et Soph. (0594)"
			      "Zeno Phil. (0595)"
			      "Zenodorus Gramm. (0597)"
			      "Rhetorica Anonyma (0598)"
			      "<Zaleucus Nomographus> <Phil.> (0601)"
			      "Comica Adespota (FCG) (0602)"
			      "Silenus Trag. (0603)"
			      "Ptolemaeus IV Philopator Trag. (0604)"
			      "Polybius Rhet. (0605)"
			      "Rufus Soph. (0606)"
			      "Aelius Theon Rhet. (0607)"
			      "Satyrus Biogr. (0608)"
			      "Tryphon I Gramm. (0609)"
			      "Alcidamas Rhet. (0610)"
			      "Theodorus Trag. (0611)"
			      "Dio Chrysostomus Soph. (0612)"
			      "<Demetrius> Rhet. (0613)"
			      "Valerius Babrius Scr. Fab. (0614)"
			      "Aspasius Phil. (0615)"
			      "Polyaenus Rhet. (0616)"
			      "Anaximenes Phil. (0617)"
			      "Antigoni Epistula (0618)"
			      "Apollonius Phil. (0619)"
			      "Archytas Phil. (0620)"
			      "[Ath]enodorus Trag. (0621)"
			      "Cleobuli Epistula (0622)"
			      "Cratetis Epistulae (0623)"
			      "Demetrius Hist. et Phil. (0624)"
			      "Polemaeus Trag. (0625)"
			      "Heraclitus Phil. (0626)"
			      "Hippocrates Med. et Corpus Hippocraticum (0627)"
			      "Gaius Musonius Rufus Phil. (0628)"
			      "Periander <Phil.> (0629)"
			      "Pherecydes Myth. et Phil. (0630)"
			      "Pittacus <Lyr.> (0631)"
			      "<Pythagoras> Phil. (0632)"
			      "<Lysis> Phil. (0633)"
			      "Xenocrates Phil. (0634)"
			      "Zeno Phil. (0635)"
			      "Socratis Epistulae (0636)"
			      "Socraticorum Epistulae (0637)"
			      "Flavius Philostratus Soph. (0638)"
			      "Menecrates Med. (0639)"
			      "Alciphron Rhet. et Soph. (0640)"
			      "Xenophon Scr. Erot. (0641)"
			      "Anonymus Londinensis Med. (0643)"
			      "Aristophanes Gramm. (0644)"
			      "Justinus Martyr Apol. (0645)"
			      "Pseudo-Justinus Martyr (0646)"
			      "Triphiodorus Epic. et Gramm. (0647)"
			      "Onasander Tact. (0648)"
			      "Lesbonax Rhet. (0649)"
			      "Herodas Mimogr. (0650)"
			      "Antoninus Liberalis Myth. (0651)"
			      "Philostratus Junior Soph. (0652)"
			      "Aratus Astron. et Epic. (0653)"
			      "Lucius Annaeus Cornutus Phil. (0654)"
			      "Parthenius Myth. (0655)"
			      "Dioscorides Pedanius Med. (0656)"
			      "Crateuas Med. (0657)"
			      "Heliodorus Scr. Erot. (0658)"
			      "Comica Adespota (Suppl. Com.) (0659)"
			      "Apollonius Med. (0660)"
			      "Archigenes Med. (0661)"
			      "Comica Adespota (CGFPR) (0662)"
			      "Praecepta Salubria (0663)"
			      "Adrianus Rhet. et Soph. (0666)"
			      "Marcellinus I Med. (0667)"
			      "Aegimius (0668)"
			      "Philumenus Med. (0671)"
			      "Aeschines Socraticus Phil. (0673)"
			      "Aglaïs Poet. Med. (0676)"
			      "Aeschrion Lyr. (0679)"
			      "Aethiopis (0683)"
			      "Aethlius Hist. (0686)"
			      "Agaclytus Hist. (0687)"
			      "Agathocles Hist. (0688)"
			      "Erasistratus Med. (0690)"
			      "Harpocrationis Epistula (0691)"
			      "Albinus Phil. (0693)"
			      "Alcimus Hist. (0695)"
			      "Alcmaeonis (0696)"
			      "Cornelius Alexander Polyhist. (0697)"
			      "Alexander Rhet. (0698)"
			      "Apollodorus Trag. (0700)"
			      "Numenius Poet. Didac. (0703)"
			      "Philo Med. (0706)"
			      "Alexis Hist. (0707)"
			      "<Ammonius> Gramm. (0708)"
			      "Amphiarai Exilium (?) (0710)"
			      "Anaxagoras Phil. (0713)"
			      "Anaxarchus Phil. (0714)"
			      "Paulus Med. (0715)"
			      "Erotianus Gramm. et Med. (0716)"
			      "Hypsicles Astron. et Math. (0717)"
			      "Aëtius Med. (0718)"
			      "Aretaeus Med. (0719)"
			      "Harmodius Trag. (0720)"
			      "Anonymi Medici Med. (0721)"
			      "Oribasius Med. (0722)"
			      "Leo Phil. (0723)"
			      "Stephanus Med. et Phil. (0724)"
			      "Anaximander Phil. (0725)"
			      "Palladius Med. (0726)"
			      "Joannes Med. (0727)"
			      "Theophilus Protospatharius, Damascius et Stephanus Atheniensis Med. (0728)"
			      "Theophilus Protospatharius Med. (0729)"
			      "Meletius Med. (0730)"
			      "Adamantius Judaeus Med. (0731)"
			      "Alexander Phil. (0732)"
			      "Cassius Iatrosophista Med. (0733)"
			      "<Lucas Apostolus> Med. (0734)"
			      "Stephanus Med. (0736)"
			      "Julianus Scriptor Legis De Medicis (0737)"
			      "Hippiatrica (0738)"
			      "Jusjurandum Medicum (0740)"
			      "Hymni Anonymi (0742)"
			      "Nemesius Theol. (0743)"
			      "Alexander Med. (0744)"
			      "Hierophilus Phil. et Soph. (0745)"
			      "Theophilus Protospatharius et Stephanus Atheniensis Med. (0746)"
			      "Severus Iatrosophista Med. (0748)"
			      "Antyllus Med. (0749)"
			      "Heliodorus Trag. (0750)"
			      "Pseudo-Hippocrates Med. (0751)"
			      "Eutecnius Soph. (0752)"
			      "Alcmaeon Phil. (0766)"
			      "Theudo[tus] Trag. (0816)"
			      "Melito Trag. (0825)"
			      "Anaxion Trag. (0833)"
			      "Ctesias Hist. et Med. (0845)"
			      "Dieuches Med. (0856)"
			      "Phrynichus II Trag. (0876)"
			      "Eudemus Poet. Med. (0888)"
			      "Timesitheus Trag. (0889)"
			      "Euthydemus Med. (0897)"
			      "Cleomenes Lyr. (0900)"
			      "Lamynthius Lyr. (0918)"
			      "Oeniades Lyr. (0971)"
			      "Stesichorus II Lyr. (0981)"
			      "Thessalus Astrol. et Med. (1004)"
			      "Ostanes Magus Alchem. (1016)"
			      "Meropis (1021)"
			      "Posidonius Phil. (1052)"
			      "Isigonus Paradox. (1083)"
			      "Cleophon Trag. (1087)"
			      "Theodorides Trag. (1094)"
			      "Euaretus Trag. (1096)"
			      "Timaeus Praxidas Astrol. (1105)"
			      "Archestratus Trag. (1115)"
			      "Pseudo-Dioscorides Med. (1118)"
			      "Anaximenis Milesii Epistulae (1121)"
			      "Andron Hist. (1123)"
			      "Andronicus Rhodius Phil. (1124)"
			      "Androtion Hist. (1125)"
			      "Anonyma De Musica Scripta Bellermanniana (1127)"
			      "Anonymi Commentarius In Platonis Theaetetum (1128)"
			      "Anonymi De Barbarismo Et Soloecismo Gramm. (1129)"
			      "Anonymus Ad Avircium Marcellum Contra Cataphrygas (1131)"
			      "Anonymus Alexandri Phil. (1132)"
			      "Anonymus Diodori Phil. (1133)"
			      "Anonymus Iamblichi Phil. (1134)"
			      "Anonymus Photii Phil. (1135)"
			      "Anonymus Presbyter Scr. Eccl. (1136)"
			      "Lycon Phil. (1138)"
			      "Anonymi Historici (FGrH) (1139)"
			      "Antimachus Epic. (1141)"
			      "Antiochus Phil. (1143)"
			      "Antiochus Hist. (1145)"
			      "Antipater Phil. (1146)"
			      "Antiphon Soph. (1147)"
			      "Antonius Diogenes Scr. Erot. (1148)"
			      "Antonini Pii Imperatoris Epistula (1149)"
			      "Aphareus Rhet. (1150)"
			      "Apion Gramm. (1152)"
			      "Apocalypsis Adam (1153)"
			      "Apocalypsis Baruch (1154)"
			      "Apocalypsis Syriaca Baruchi (1155)"
			      "Apocalypsis Eliae (1156)"
			      "Apocalypsis Esdrae (1157)"
			      "Apocalypsis Joannis (1158)"
			      "Apocalypsis Sophoniae (1160)"
			      "Apocryphon Ezechiel (1161)"
			      "Apollas Hist. (1162)"
			      "Claudius Apollinarius Apol. (1163)"
			      "Apollodorus Hist. (1164)"
			      "Apollodorus Mech. (1165)"
			      "Apollodorus Phil. (1166)"
			      "Apollonius Biogr. (1167)"
			      "Apollonius Soph. (1168)"
			      "Apollonius Hist. (1170)"
			      "Apollonius Scr. Eccl. (1171)"
			      "Arcesilaus Phil. (1172)"
			      "Archedemus Phil. (1173)"
			      "Archemachus Hist. (1174)"
			      "Archestratus Parodius (1175)"
			      "Archytas Epic. (1176)"
			      "Pseudo-Archytas Phil. (1177)"
			      "<Aresas> Phil. (1178)"
			      "<Arimnestus> Phil. (1179)"
			      "<Aristaeus> Phil. (1180)"
			      "Aristarchus Astron. (1181)"
			      "[Aristeas] Epic. (1182)"
			      "Aristeae Epistula (1183)"
			      "Aristides Apol. (1184)"
			      "Aristobulus Judaeus Phil. (1186)"
			      "Aristocles Phil. (1188)"
			      "Aristocrates Hist. (1189)"
			      "Aristagoras Hist. (1190)"
			      "<Aristombrotus> Phil. (1191)"
			      "Ariston Phil. (1192)"
			      "Ariston Phil. (1193)"
			      "Aristonicus Gramm. (1194)"
			      "Aristophanes Hist. (1196)"
			      "Artemon Gramm. (1197)"
			      "Asclepiades Gramm. et Hist. (1199)"
			      "Asclepiades Myth. (1200)"
			      "Assumptio Mosis (1201)"
			      "<Athamas> Phil. (1202)"
			      "Paeanes (CA) (1203)"
			      "Athenaeus Mech. (1204)"
			      "Athenagoras Apol. (1205)"
			      "Athenodorus Phil. (1206)"
			      "Attalus Astron. et Math. (1207)"
			      "Atticus Phil. (1208)"
			      "Autolycus Astron. (1210)"
			      "Balagrus Hist. (1211)"
			      "Atridarum Reditus (1212)"
			      "Julia Balbilla Lyr. (1213)"
			      "Barnabae Epistula (1216)"
			      "Basilis Hist. (1218)"
			      "Bato Hist. et Rhet. (1219)"
			      "Batrachomyomachia (1220)"
			      "Beros(s)us Astrol. et Hist. (1222)"
			      "Bias <Phil.> (1223)"
			      "Bion Phil. (1224)"
			      "Bion Hist. (1225)"
			      "Biton Mech. (1226)"
			      "Blaesus Comic. (1227)"
			      "[Boeo] Epic. (1228)"
			      "[Boeus] Epic. (1229)"
			      "<Brotinus> Phil. (1230)"
			      "<Bryson> Phil. (1231)"
			      "<Butherus> Phil. (1232)"
			      "<Callicratidas> Phil. (1237)"
			      "Domitius Callistratus Hist. (1239)"
			      "Callixenus Hist. (1240)"
			      "Carmen Naupactium (1241)"
			      "Canon Librorum (1242)"
			      "Carneiscus Phil. (1244)"
			      "Carystius Hist. (1245)"
			      "<Cebes> Phil. (1247)"
			      "Celsus Phil. (1248)"
			      "Cephalion Hist. et Rhet. (1249)"
			      "Cercidas Iamb. (1250)"
			      "Chamaeleon Phil. (1251)"
			      "Certamen Homeri Et Hesiodi (1252)"
			      "Charax Hist. (1254)"
			      "Chares Gnom. (1256)"
			      "Charinus Choliamb. (1257)"
			      "Charon Hist. (1258)"
			      "<Charondas Nomographus> <Phil.> (1259)"
			      "[Chersias] Epic. (1260)"
			      "Choerilus Epic. (1262)"
			      "Choerilus Epic. (1263)"
			      "Chrysippus Phil. (1264)"
			      "Tyrannion Gramm. (1266)"
			      "Claudius Iolaus Hist. (1268)"
			      "Cleanthes Phil. (1269)"
			      "Clearchus Phil. (1270)"
			      "Clemens Romanus Theol. et Clementina (1271)"
			      "Cleomedes Astron. (1272)"
			      "Cleon Eleg. (1273)"
			      "Cleobulus Epigr. et Lyr. (1274)"
			      "Cleostratus Poet. Phil. (1275)"
			      "Clidemus Hist. (1276)"
			      "<Clinias> Phil. (1277)"
			      "Clitarchus Gnom. (1278)"
			      "[Clitophon] Hist. (1281)"
			      "Clytus Hist. (1282)"
			      "Conon Hist. (1285)"
			      "Corpus Hermeticum (1286)"
			      "Crantor Phil. (1287)"
			      "Craterus Hist. (1288)"
			      "Crates Hist. (1289)"
			      "Creophylus Hist. (1291)"
			      "Crito Phil. (1292)"
			      "Crinis Phil. (1293)"
			      "Critolaus Phil. (1294)"
			      "Cypria (1296)"
			      "Damippus Phil. (1297)"
			      "Demetrii Phalerei Epistula (1298)"
			      "Demetrius Poet. Phil. (1301)"
			      "Demetrius Rhet. (1302)"
			      "Demochares Hist. et Orat. (1303)"
			      "Democritus Phil. (1304)"
			      "Democritus Hist. (1305)"
			      "Bolus Med. et Phil. (1306)"
			      "Demon Hist. (1307)"
			      "Demosthenes Epic. (1308)"
			      "Dialexeis  (Δισσοὶ λόγοἰ (1309)"
			      "Dictys Hist. (1310)"
			      "Didache XII Apostolorum (1311)"
			      "Didymus Gramm. (1312)"
			      "Dieuchidas Hist. (1313)"
			      "Dinias Hist. (1314)"
			      "Dinolochus Comic. (1315)"
			      "Dinon Hist. (1316)"
			      "Diodorus Rhet. (1318)"
			      "Diogenes Phil. (1319)"
			      "Diogenes Phil. (1320)"
			      "Diogenes Phil. (1321)"
			      "Diogenianus Phil. (1322)"
			      "Aelius Dionysius Attic. (1323)"
			      "Dionysius Hist. (1324)"
			      "Diogenis Sinopensis Epistulae (1325)"
			      "Dionysius Epic. (1326)"
			      "Dionis Epistulae (1327)"
			      "Dionysius Hist. (1328)"
			      "Dionysius Scr. Eccl. (1329)"
			      "<Diotogenes> Phil. (1332)"
			      "Dius Phil. (1334)"
			      "Dorotheus Astrol. (1337)"
			      "Dosiadas Hist. (1338)"
			      "Duris Hist. (1339)"
			      "<Eccelus> Phil. (1340)"
			      "<Ecphantus> Phil. (1341)"
			      "Empedocles Poet. Phil. (1342)"
			      "Eparchides Hist. (1343)"
			      "Epica Adespota (CA) (1344)"
			      "Epica Incerta (CA) (1345)"
			      "Ephraem Scr. Eccl. (1346)"
			      "Epimenides Phil. (1347)"
			      "Epistula A Martyribus Lugdunensibus (1349)"
			      "Epistula Ad Diognetum (1350)"
			      "Epigoni (1351)"
			      "Epistula Ecclesiarum Apud Lugdunum Et Viennam (1352)"
			      "Epitaphium Abercii (1353)"
			      "Ergias Hist. (1354)"
			      "Erinna Lyr. (1355)"
			      "Eudemus Phil. (1357)"
			      "Eudoxus Astron. (1358)"
			      "<Euryphamus> Phil. (1360)"
			      "Eumedes Comic. (1361)"
			      "<Eurytus> Phil. (1362)"
			      "Evangelium Aegyptium (1364)"
			      "Melampus Scriptor De Divinatione (1365)"
			      "Evangelium Bartholomaei (1366)"
			      "Euripidis Epistulae (1367)"
			      "Evangelium Ebionitum (1368)"
			      "Evangelium Mariae (1369)"
			      "Evangelium Petri (1371)"
			      "Evangelium Evae (1372)"
			      "Evangelium Philippi (1373)"
			      "Evangelium Secundum Hebraeos (1374)"
			      "Evangelium Thomae (1375)"
			      "Eudemus Rhet. (1376)"
			      "Favorinus Phil. et Rhet. (1377)"
			      "Fragmenta Alchemica (1379)"
			      "Fragmentum Synodicae Epistulae Concilii Caesariensis (1381)"
			      "Fragmentum Teliambicum (1382)"
			      "Geminus Astron. (1383)"
			      "Historia Alexandri Magni (1386)"
			      "(H)agias-Dercylus Hist. (1387)"
			      "Harmodius Hist. (1388)"
			      "Harpocration Gramm. (1389)"
			      "Hecataeus Hist. (1390)"
			      "Hegemon Epic. (1391)"
			      "Hegesander Hist. (1392)"
			      "Hegesianax Astron. et Epic. (1393)"
			      "[Hegesinus] Epic. (1395)"
			      "Hegesippus Hist. (1397)"
			      "Hegesippus Scr. Eccl. (1398)"
			      "Pamphilus Trag. (1399)"
			      "Heliodorus Perieg. (1400)"
			      "Hephaestion Gramm. (1402)"
			      "Heraclides Criticus Perieg. (1405)"
			      "Heraclides Hist. (1406)"
			      "Heraclides Lembus Hist. (1407)"
			      "Heraclides Gramm. (1408)"
			      "Heraclides Ponticus Phil. (1409)"
			      "Heracliti Ephesii Epistulae (1411)"
			      "Pseudo-Heracliti Epistulae (1412)"
			      "Heraclitus Paradox. (1413)"
			      "Heraclitus Phil. (1414)"
			      "(H)eren(n)ius Philo Gramm. et Hist. (1416)"
			      "Hermas Scr. Eccl. Pastor Hermae (1419)"
			      "Hermias Iamb. (1420)"
			      "Hermippus Gramm. et Hist. (1421)"
			      "Hermonax Epic. (1425)"
			      "Herodes Atticus Soph. (1426)"
			      "Herodorus Hist. (1427)"
			      "Hestiaeus Hist. (1428)"
			      "Hierocles Phil. (1429)"
			      "Hieronymus Phil. (1430)"
			      "Hipparchus Astron. et Geogr. (1431)"
			      "<Hipparchus> Phil. (1432)"
			      "Hipparchus <Epigr.> (1433)"
			      "Hippias Soph. (1434)"
			      "Hippias Hist. (1435)"
			      "<Hippodamus> Phil. (1436)"
			      "Hippon Phil. (1437)"
			      "Hippys Hist. (1438)"
			      "Hermarchus Phil. (1439)"
			      "Iamblichus Scr. Erot. (1441)"
			      "Idomeneus Hist. (1442)"
			      "Ignatius Scr. Eccl. (1443)"
			      "Ilias Parva (1444)"
			      "Iliu Persis (1445)"
			      "Ion Eleg. (1446)"
			      "Irenaeus Theol. (1447)"
			      "Ister Hist. (1450)"
			      "Josephus Et Aseneth (1451)"
			      "Juba II Rex Mauretaniae <Hist.> (1452)"
			      "Lepidus Hist. (1459)"
			      "Lesbonax Gramm. (1460)"
			      "Leucippus Phil. (1461)"
			      "Liber Eldad Et Modad (1462)"
			      "Liber Enoch (1463)"
			      "Liber Jubilaeorum (1464)"
			      "Lollianus Scr. Erot. (1466)"
			      "Lyceas Hist. (1469)"
			      "Lycus Hist. (1470)"
			      "Lyrica Adespota (SLG) (1471)"
			      "Maiistas Epic. (1475)"
			      "Mamercus Eleg. (1476)"
			      "Manetho Hist. (1477)"
			      "Marci Aurelii Epistula (1479)"
			      "Cyranides (1482)"
			      "Martyrium Et Ascensio Isaiae (1483)"
			      "Martyrium Polycarpi (1484)"
			      "Martyrium Ptolemaei Et Lucii (1485)"
			      "Matron Parodius (1486)"
			      "Maximus Astrol. (1487)"
			      "Maximus Theol. (1488)"
			      "Megasthenes Hist. (1489)"
			      "<Megillus> Phil. (1490)"
			      "Melanthius Hist. (1491)"
			      "Melinno Lyr. (1493)"
			      "Melissus Phil. (1494)"
			      "Melito Apol. (1495)"
			      "Memnon Hist. (1496)"
			      "Menander Hist. (1498)"
			      "Menecles Hist. (1499)"
			      "Menecrates Poet. Phil. (1500)"
			      "Menecrates Hist. (1503)"
			      "Menelaus Epic. (1504)"
			      "Menesthenes Hist. (1505)"
			      "Menodotus Hist. (1506)"
			      "<Metopus> Phil. (1507)"
			      "Metrodorus Phil. (1508)"
			      "<Milon> <Phil.> (1509)"
			      "Mimnermus Trag. (1511)"
			      "Minyas (1512)"
			      "Mnaseas Perieg. (1514)"
			      "Moeris Attic. (1515)"
			      "Molpis Hist. (1516)"
			      "Vita Et Sententiae Secundi (1521)"
			      "Myron Hist. (1523)"
			      "Naumachius Epic. (1524)"
			      "Neanthes Hist. (1525)"
			      "Neoptolemus Gramm. (1526)"
			      "Nepualius Med. et Phil. (1527)"
			      "Nicander Gramm. (1529)"
			      "Nicanor Gramm. (1530)"
			      "Nicias Epigr. (1533)"
			      "Nicocles Hist. (1534)"
			      "Nicocrates Hist. (1535)"
			      "Nostoi (1541)"
			      "Numenius Phil. (1542)"
			      "Nymphis Hist. (1544)"
			      "Ocellus Phil. (1545)"
			      "Oechaliae Halosis (1546)"
			      "Oedipodea (1547)"
			      "Oenomaus Phil. (1548)"
			      "<Onatas> Phil. (1549)"
			      "Oracula Chaldaica (1550)"
			      "Oracula Sibyllina (1551)"
			      "Oratio Josephi (1552)"
			      "<Palaephatus> Myth. (1553)"
			      "Pancrates Epic. (1555)"
			      "Pancrates Epigr. (1556)"
			      "Panyassis Epic. (1557)"
			      "Papias Scr. Eccl. (1558)"
			      "Bucolicum (1559)"
			      "Matthiae Traditiones (1560)"
			      "Parmenides Poet. Phil. (1562)"
			      "Parmeno Iamb. (1566)"
			      "Parrhasius Epigr. (1567)"
			      "Parthax Hist. (1568)"
			      "Pausanias Attic. (1569)"
			      "Epitaphium Pectorii (1570)"
			      "<Pempelus> Phil. (1571)"
			      "<Perictione> Phil. (1572)"
			      "Persaeus Phil. (1574)"
			      "Phaedimus <Epic.> (1576)"
			      "Phaedimus Epigr. (1577)"
			      "Phaenias Phil. (1578)"
			      "Phaestus Epic. (1580)"
			      "Phanodemus Hist. (1583)"
			      "Pherecydes Hist. (1584)"
			      "Pherecydis Epistula (1585)"
			      "Philiades Eleg. (1587)"
			      "Philicus Lyr. (1588)"
			      "Philippus Hist. (1590)"
			      "Philistus Hist. (1591)"
			      "Philo Judaeus Senior Epic. (1594)"
			      "Philodemus Phil. (1595)"
			      "Philolaus Phil. (1596)"
			      "<Telauges> Phil. (1597)"
			      "Philo Mech. (1599)"
			      "Philostratus Major Soph. (1600)"
			      "Philoxenus Gramm. (1602)"
			      "<Phintys> Phil. (1603)"
			      "Phocylides Eleg. et Gnom. (1604)"
			      "Pseudo-Phocylides Gnom. (1605)"
			      "Phoenix Iamb. (1606)"
			      "Phoronis (1607)"
			      "Phrynichus Attic. (1608)"
			      "Phylarchus Hist. (1609)"
			      "Tyrannion Junior Gramm. (1611)"
			      "Pittaci Epistula (1613)"
			      "Platonius Gramm. (1615)"
			      "Marcus Antonius Polemon Soph. (1617)"
			      "Polycarpus Scr. Eccl. (1622)"
			      "Polycharmus Hist. (1623)"
			      "Polyclitus Phil. (1625)"
			      "Polycrates Scr. Eccl. (1626)"
			      "Polycrates Hist. (1627)"
			      "Polystratus Phil. (1629)"
			      "Posidippus Epigr. (1632)"
			      "Praxiteles <Epigr.> (1633)"
			      "Prodicus Soph. (1634)"
			      "Protagoras Soph. (1635)"
			      "Protagorides Hist. (1636)"
			      "Protevangelium Jacobi (1637)"
			      "Proxenus Hist. (1638)"
			      "Pseudo-Auctores Hellenistae (PsVTGr) (1639)"
			      "Ptolemaeus Gnost. (1641)"
			      "Pseudo-Ptolemaeus (1642)"
			      "Ptolemaeus Gramm. (1643)"
			      "Ptolemaeus VIII Euergetes II <Hist.> (1645)"
			      "Ptolemaeus Hist. (1646)"
			      "Pyrgion Hist. (1648)"
			      "Pythaenetus Hist. (1649)"
			      "Pytheas Perieg. (1650)"
			      "Pythermus Hist. (1651)"
			      "Rhinthon Comic. (1654)"
			      "Satyrus Hist. (1661)"
			      "Sciras Comic. (1662)"
			      "Semus Gramm. (1663)"
			      "Seniores Alexandrini Scr. Eccl. (1664)"
			      "Seniores Apud Irenaeum Scr. Eccl. (1665)"
			      "Sententiae Sexti (1666)"
			      "<Septem Sapientes> Phil. (1667)"
			      "Serapion Scr. Eccl. (1670)"
			      "Simylus Eleg. (1675)"
			      "Simylus Iamb. (1676)"
			      "Socrates Hist. (1678)"
			      "Socrates Hist. (1679)"
			      "<Sodamus> Eleg. (1680)"
			      "Solonis Epistulae (1681)"
			      "Sopater Comic. (1682)"
			      "Sophaenetus Hist. (1683)"
			      "Sosibius Gramm. (1685)"
			      "Sosicrates Hist. (1687)"
			      "Sostratus Gramm. (1688)"
			      "Sotadea (1690)"
			      "Sotades Iamb. (1691)"
			      "Speusippus Phil. (1692)"
			      "Sphaerus Phil. (1693)"
			      "<Sthenidas> Phil. (1695)"
			      "Straton Phil. (1696)"
			      "Telephus Gramm. (1698)"
			      "Teles Phil. (1699)"
			      "Testamenta XII Patriarcharum (1700)"
			      "Testamentum Abrahae (1701)"
			      "Testamentum Jobi (1702)"
			      "Teucer Astrol. (1703)"
			      "Teucer Hist. (1704)"
			      "Thales Phil. (1705)"
			      "Thallus Hist. (1706)"
			      "Theagenes Hist. (1709)"
			      "<Theages> Phil. (1710)"
			      "<Thearidas> Phil. (1711)"
			      "Thebaïs (1712)"
			      "Themison Hist. (1713)"
			      "Theocritus Soph. (1714)"
			      "Theodoridas Epigr. (1715)"
			      "Theodosius Astron. et Math. (1719)"
			      "Theodotus Judaeus Epic. (1720)"
			      "Theolytus Epic. (1723)"
			      "Theon Phil. (1724)"
			      "Theophilus Apol. (1725)"
			      "Theopompus Epic. (1726)"
			      "Theotimus Hist. (1727)"
			      "Theseus Hist. (1728)"
			      "Thrasymachus Rhet. et Soph. (1729)"
			      "Timachidas Hist. (1732)"
			      "Timaeus Hist. (1733)"
			      "Timaeus Phil. (1734)"
			      "Timon Phil. (1735)"
			      "Timonax Hist. (1736)"
			      "Titanomachia (1737)"
			      "Tragica Adespota (1738)"
			      "Valentinus Gnost. (1746)"
			      "Vita Adam Et Evae (1747)"
			      "Sosigenes Phil. (1748)"
			      "Vitae Hesiodi Particula (1749)"
			      "Vitae Prophetarum (1750)"
			      "Xanthus Hist. (1751)"
			      "Xenagoras Geogr. et Hist. (1752)"
			      "Xenion Hist. (1753)"
			      "Xenophontis Epistulae (1754)"
			      "Demetrius Gramm. (1756)"
			      "Julius Epic. (1757)"
			      "Sententiae Pythagoreorum (1759)"
			      "Gaius Suetonius Tranquillus Gramm. et Hist. (1760)"
			      "Tryphon II Gramm. (1763)"
			      "Vettius Valens Astrol. (1764)"
			      "Vitae Aesopi (1765)"
			      "Tatianus Apol. (1766)"
			      "Montanus et Montanistae Theol. (1771)"
			      "Paraleipomena Jeremiou (1772)"
			      "Pseudo-Agathon Epigr. (1775)"
			      "Anonymus Epicureus Phil. (1779)"
			      "Alcimenes Comic. (1780)"
			      "Philippus Comic. (1781)"
			      "Augeas Comic. (1782)"
			      "Callicrates Comic. (1783)"
			      "<Heraclitus> Comic. (1784)"
			      "Paramonus Comic. (1785)"
			      "Sogenes Comic. (1786)"
			      "[Menippus] Comic. (1787)"
			      "Phormis Comic. (1788)"
			      "Menandri Et Philistionis Sententiae (1791)"
			      "Biottus Comic. (1792)"
			      "Timoxenus Comic. (1793)"
			      "Philocles Comic. (1794)"
			      "Chaerion Comic. (1795)"
			      "Choliambica Adespota (ALG) (1797)"
			      "Euclides Geom. (1799)"
			      "Euboeus Parodius (1800)"
			      "Parodica Anonyma (1801)"
			      "Homerica (1802)"
			      "Bruti Epistulae (1803)"
			      "Ninus (1804)"
			      "Vitae Homeri (1805)"
			      "Metrodorus Major Phil. (1811)"
			      "Demaratus Hist. (1812)"
			      "Anonymus De Plantis Aegyptiis (1813)"
			      "Ptolemais Phil. (1814)"
			      "Sappho et Alcaeus Lyr. (1815)"
			      "Epica Adespota (GDRK) (1816)"
			      "Fragmenta Anonyma (PsVTGr) (1817)"
			      "Pseudo-Demosthenes Epigr. (1819)"
			      "Iambica Adespota (ALG) (1821)"
			      "Pamphila Hist. (1828)"
			      "Acesander Hist. (1832)"
			      "Pratinas Trag. (1833)"
			      "Agroetas Hist. (1835)"
			      "Anonymi Aulodia (1836)"
			      "Theon Gramm. (1838)"
			      "Polyphrasmon Trag. (1839)"
			      "Euripides II Trag. (1840)"
			      "Nicomachus Trag. (1843)"
			      "Hera[clides] Trag. (1844)"
			      "Callistratus Trag. (1845)"
			      "Spintharus Trag. (1846)"
			      "Meletus Junior Trag. (1848)"
			      "Demetrius Trag. (1849)"
			      "Oratio Manassis (1858)"
			      "Liber Jannes Et Jambres (1859)"
			      "Crito Hist. (1867)"
			      "Damastes Hist. (1868)"
			      "Bion Hist. (1871)"
			      "Aristodemus Hist. et Myth. (1875)"
			      "Dionysius Scytobrachion Gramm. (1881)"
			      "Moderatus Phil. (1890)"
			      "[Dositheus] Hist. (1896)"
			      "Aristonicus Hist. (1899)"
			      "Simonides Epic. (1906)"
			      "Cratippus Hist. (1907)"
			      "Daimachus Hist. (1908)"
			      "Diyllus Hist. (1911)"
			      "Euphantus Phil. (1912)"
			      "Eudoxus Hist. (1915)"
			      "Demetrius Hist. (1917)"
			      "Timagenes Hist. (1918)"
			      "Stesimbrotus Hist. (1923)"
			      "Leo Hist. (1941)"
			      "Antigenes Hist. (1945)"
			      "Potamon Hist. (1949)"
			      "Hieronymus Hist. (1953)"
			      "Heraclides Phil. (1954)"
			      "Leschides Epic. (1967)"
			      "Philinus Hist. (1969)"
			      "Silenus Hist. (1970)"
			      "Eumachus Hist. (1972)"
			      "Metrodorus Hist. (1976)"
			      "Lucius Licinius Lucullus Hist. (1977)"
			      "Leo Hist. (1978)"
			      "Theophanes Hist. (1981)"
			      "Theodorus Poeta (1987)"
			      "Ariston Apol. (1992)"
			      "Plotinus Phil. (2000)"
			      "Themistius Phil. et Rhet. (2001)"
			      "Anonymus Seguerianus Rhet. (2002)"
			      "Flavius Claudius Julianus Imperator Phil. Julian the Apostate (2003)"
			      "Amelii Epistula (2004)"
			      "Martyrium Pionii (2005)"
			      "Synesius Phil. (2006)"
			      "Martyrium Potamiaenae Et Basilidis (2007)"
			      "Martyrium Cononis (2008)"
			      "Martyrium Marini (2009)"
			      "Martyrium Dasii (2010)"
			      "Martyrium Agapae, Irenae, Chionae Et Sodalium (2011)"
			      "Acta Eupli (2012)"
			      "Acta Phileae (2014)"
			      "Testamentum XL Martyrum (2015)"
			      "Passio Perpetuae Et Felicitatis (2016)"
			      "Gregorius Nyssenus Theol. (2017)"
			      "Eusebius Scr. Eccl. et Theol. (2018)"
			      "Pelagius Alchem. (2019)"
			      "Theodosius Gramm. (2020)"
			      "Epiphanius Scr. Eccl. (2021)"
			      "Gregorius Nazianzenus Theol. (2022)"
			      "Iamblichus Phil. (2023)"
			      "Maximus Rhet. (2025)"
			      "Valerius Apsines Rhet. (2027)"
			      "Anonymi Geographia In Sphaera Intelligenda (2029)"
			      "Geographica Adespota (GGM) (2030)"
			      "Sopater Rhet. (2031)"
			      "Pappus Math. (2032)"
			      "Theon Math. (2033)"
			      "Porphyrius Phil. (2034)"
			      "Athanasius Theol. (2035)"
			      "Dexippus Phil. (2036)"
			      "Joannes Stobaeus Anthologus (2037)"
			      "Acta Thomae (2038)"
			      "Diophantus Math. (2039)"
			      "Basilius Theol. (2040)"
			      "Marcellus Theol. (2041)"
			      "Origenes Theol. (2042)"
			      "Hephaestion Astrol. (2043)"
			      "Nonnus Epic. (2045)"
			      "Quintus Epic. (2046)"
			      "Syriani, Sopatri Et Marcellini Scholia Ad Hermogenis Status (2047)"
			      "Salaminius Hermias Sozomenus Scr. Eccl. (2048)"
			      "Sallustius Phil. (2049)"
			      "Eunapius Hist. et Soph. (2050)"
			      "Himerius Soph. (2051)"
			      "Horapollo Gramm. (2052)"
			      "Paulus Astrol. (2053)"
			      "Aristides Quintilianus Mus. (2054)"
			      "Serenus Geom. (2055)"
			      "Socrates Scholasticus Hist. (2057)"
			      "Philostorgius Scr. Eccl. (2058)"
			      "Alexander Theol. (2059)"
			      "Asterius Scr. Eccl. (2060)"
			      "Asterius Sophista Scr. Eccl. (2061)"
			      "Joannes Chrysostomus Scr. Eccl. John Chrysostom (2062)"
			      "Gregorius Thaumaturgus Scr. Eccl. (2063)"
			      "Acacius Theol. (2064)"
			      "Apollinaris Theol. (2074)"
			      "Basilius Med. et Scr. Eccl. (2084)"
			      "Didymus Caecus Scr. Eccl. Didymus the Blind (2102)"
			      "Pseudo-Macarius Scr. Eccl. (2109)"
			      "Cyrillus Scr. Eccl. (2110)"
			      "Palladius Scr. Eccl. (2111)"
			      "Amphilochius Scr. Eccl. (2112)"
			      "Hippolytus Scr. Eccl. (2115)"
			      "Arcadius Gramm. (2116)"
			      "Anonymus De Metrorum Ratione (2117)"
			      "Gryllus (2118)"
			      "Christodorus Epic. (2119)"
			      "Panteleius Epic. (2120)"
			      "Dioscorus Poeta (2121)"
			      "Gaius Asinius Quadratus Hist. (2122)"
			      "Troilus Soph. (2127)"
			      "Arethas Philol. et Scr. Eccl. (2130)"
			      "Achilles Tatius Astron. (2133)"
			      "Iamblichus Alchem. (2140)"
			      "Publius Herennius Dexippus Hist. (2141)"
			      "Aristodemus Hist. (2148)"
			      "Praxagoras Hist. (2151)"
			      "Bion Math. et Phil. (2153)"
			      "Magnus Hist. (2157)"
			      "Eutychianus Hist. (2158)"
			      "Pyrrhus Hist. (2160)"
			      "Aratus Hist. (2162)"
			      "Apollophanes Phil. (2168)"
			      "Herillus Phil. (2169)"
			      "Stesiclides Hist. (2171)"
			      "Andron Hist. (2172)"
			      "Antileon Hist. (2173)"
			      "<Autocharis> Hist. (2175)"
			      "Cassius Longinus Phil. et Rhet. (2178)"
			      "Moses Alchem. (2181)"
			      "Staphylus Hist. (2182)"
			      "Dionysius Μεταθέμενος Phil. (2185)"
			      "Leo Hist. (2186)"
			      "Posidonius Hist. (2187)"
			      "Callinicus Soph. (2189)"
			      "[Clitonymus] Hist. (2190)"
			      "[Agatharchides] Hist. (2192)"
			      "[Aretades] Hist. (2193)"
			      "[Aristides] Hist. (2194)"
			      "[Chrysermus] Hist. (2195)"
			      "[Dercyllus] Hist. (2196)"
			      "Libanius Rhet. et Soph. (2200)"
			      "[Ctesiphon] Hist. (2201)"
			      "[Menyllus] Hist. (2202)"
			      "[Theophilus] Hist. (2203)"
			      "Autocrates Hist. (2204)"
			      "Autesion Hist. (2205)"
			      "Anaxicrates Hist. (2210)"
			      "Lyceas Hist. (2212)"
			      "[Timotheus] Hist. (2213)"
			      "Ar(i)aethus Hist. (2215)"
			      "Aristippus Hist. (2216)"
			      "Nicias Hist. (2217)"
			      "Calliphon et Democedes Med. et Phil. (2218)"
			      "Amelesagoras Hist. (2219)"
			      "Parm(en)iscus Phil. (2225)"
			      "Iccus Phil. (2226)"
			      "Paron Phil. (2227)"
			      "Menestor Phil. (2228)"
			      "Xuthus Phil. (2229)"
			      "Boïdas Phil. (2230)"
			      "Thrasyalces Phil. (2231)"
			      "Damon Mus. (2232)"
			      "Pseudo-Polemon (2233)"
			      "Oenopides Phil. (2234)"
			      "Hippocrates Math. (2235)"
			      "Eutropius Hist. (2236)"
			      "Theodorus Math. (2237)"
			      "Pythagoristae (D-K) Phil. (2239)"
			      "Hicetas Phil. (2240)"
			      "Xenophilus Mus. et Phil. (2241)"
			      "Echecrates Phil. (2242)"
			      "Apocalypsis Sedrach (2243)"
			      "Damon et Phintias Phil. (2244)"
			      "Simus Phil. (2245)"
			      "Lycon Phil. (2246)"
			      "Petron Phil. (2247)"
			      "Acta Xanthippae Et Polyxenae (2248)"
			      "Gorgias Hist. (2255)"
			      "Hippasus Phil. (2260)"
			      "Diodorus Perieg. (2265)"
			      "Timagoras Hist. (2268)"
			      "Callippus Hist. (2270)"
			      "Damon Hist. (2273)"
			      "Hesychius Illustrius Hist. (2274)"
			      "Theagenes Phil. (2275)"
			      "Hypermenes Hist. (2277)"
			      "Phanodicus Hist. (2278)"
			      "Melisseus Hist. (2282)"
			      "Anaxandridas Hist. (2284)"
			      "Cercops Phil. (2286)"
			      "Fragmentum Stoicum (2287)"
			      "Echephylidas Hist. (2289)"
			      "Cratylus Phil. (2291)"
			      "Zeno Phil. (2294)"
			      "Lysanias Hist. (2298)"
			      "Promathidas Hist. (2300)"
			      "Archelaus Phil. (2303)"
			      "Idaeus Phil. (2304)"
			      "Clidemus Phil. (2305)"
			      "Xenomedes Hist. (2306)"
			      "Artemon Hist. (2307)"
			      "Antisthenes Phil. (2313)"
			      "Diogenes Phil. (2314)"
			      "Hermias Phil. (2317)"
			      "Apollodorus Phil. (2319)"
			      "Antenor Hist. (2322)"
			      "Dei(l)ochus Hist. (2326)"
			      "Diogenes Hist. (2328)"
			      "Scamon Hist. (2330)"
			      "Myrsilus Hist. (2331)"
			      "Possis Hist. (2333)"
			      "Nausiphanes Phil. (2334)"
			      "Hereas Hist. (2336)"
			      "Maeandrius Hist. (2339)"
			      "Diotimus Phil. (2340)"
			      "Aristocritus Hist. (2341)"
			      "Agl(a)osthenes Hist. (2345)"
			      "Andriscus Hist. (2346)"
			      "[Pyrander] Hist. (2349)"
			      "Dionysius Hist. (2354)"
			      "Xeniades Soph. (2355)"
			      "Gorgon Hist. (2357)"
			      "Zeno Hist. (2364)"
			      "Theognis Hist. (2367)"
			      "Chronicon Paschale (2371)"
			      "Euagon Hist. (2372)"
			      "Diodorus Phil. (2383)"
			      "Hermias Hist. (2384)"
			      "Polycritus Hist. (2385)"
			      "Timonides Hist. (2386)"
			      "Athanis Hist. (2387)"
			      "Hippostratus Hist. (2391)"
			      "Artemon Hist. (2392)"
			      "Andreas Hist. (2393)"
			      "Hyperochus Hist. (2396)"
			      "Boethus Phil. (2397)"
			      "Basilides Phil. (2398)"
			      "Eudromus Phil. (2399)"
			      "Philogelos (2404)"
			      "Dioscurides Hist. (2409)"
			      "Androetas Hist. (2412)"
			      "Cineas Rhet. (2417)"
			      "Archinus Hist. (2418)"
			      "Asclepiades Gramm. et Hist. (2423)"
			      "Chaeremon Hist. et Phil. (2424)"
			      "Hermaeus Hist. (2426)"
			      "Thrasyllus Hist. (2428)"
			      "Aelius Dius Hist. (2434)"
			      "Lycophron Soph. (2444)"
			      "Amometus Hist. (2445)"
			      "Timotheus Gramm. (2449)"
			      "Aristocreon Hist. (2455)"
			      "Nessas Phil. (2456)"
			      "Marcellus Hist. (2458)"
			      "Glaucus Hist. (2460)"
			      "Uranius Hist. (2461)"
			      "Dionysius Hist. (2466)"
			      "Nicander Hist. (2474)"
			      "Menecrates Hist. (2475)"
			      "Patrocles Hist. (2479)"
			      "Daimachus Hist. (2482)"
			      "Eustochius Soph. (2499)"
			      "Capito Hist. (2506)"
			      "Demetrius Hist. (2511)"
			      "Paeon Hist. (2512)"
			      "Laetus Hist. (2525)"
			      "Metrophanes Hist. (2531)"
			      "[Hermesianax] Hist. (2532)"
			      "Timolaus Hist. (2533)"
			      "Andron Geogr. (2536)"
			      "Diophantus Hist. (2539)"
			      "Quintus Fabius Pictor Hist. (2542)"
			      "Lucius Cincius Alimentus Hist. (2543)"
			      "Gaius Acilius Hist. et Phil. (2545)"
			      "Publius Rutilius Rufus Hist. (2546)"
			      "Antigonus (2547)"
			      "Promathion Hist. (2548)"
			      "Critolaus Hist. (2552)"
			      "Agesilaus Hist. (2555)"
			      "[Alexarchus] Hist. (2556)"
			      "[Aristobulus] Hist. (2557)"
			      "[Chrysippus] Hist. (2559)"
			      "Pythocles Hist. (2560)"
			      "Mnesimachus Hist. (2565)"
			      "[Agathon] Hist. (2566)"
			      "[Sosthenes] Hist. (2568)"
			      "Hierocles Phil. (2571)"
			      "Pausanias Hist. (2573)"
			      "Anatolius Math. et Phil. (2577)"
			      "Joannes Gramm. et Poeta (2578)"
			      "Joannes Laurentius Lydus Hist. (2580)"
			      "Manetho Astrol. (2583)"
			      "Marcellinus Biogr. (2585)"
			      "Menander Rhet. (2586)"
			      "Ariston Phil. (2587)"
			      "Olympiodorus Alchem. (2589)"
			      "Orion Gramm. (2591)"
			      "Joannes Pediasimus Philol. et Rhet. (2592)"
			      "Phillis Hist. (2594)"
			      "Philo Paradox. (2595)"
			      "Phoebammon Soph. (2596)"
			      "Procopius Rhet. et Scr. Eccl. (2598)"
			      "Simon Scriptor De Re Equestri (2600)"
			      "Tiberius Rhet. (2601)"
			      "Timaeus Sophista Gramm. (2602)"
			      "Ulpianus Gramm. et Rhet. (2604)"
			      "Agamestor Eleg. (2605)"
			      "Agathyllus Eleg. (2606)"
			      "Alexinus Phil. (2607)"
			      "Archebulus Poeta (2608)"
			      "Asopodorus Iamb. (2609)"
			      "Boiscus Iamb. (2610)"
			      "Butas Eleg. (2611)"
			      "Caecalus (?) Epic. (2612)"
			      "Callimachus Junior Epic. (2613)"
			      "Cleomachus Poeta (2614)"
			      "Daphitas Gramm. vel Soph. (2615)"
			      "Demareta Poeta (2616)"
			      "Demetrius Poeta (2617)"
			      "Didymarchus Poeta (2618)"
			      "Dionysius Epic. (2619)"
			      "Dionysius Iambus Gramm. et Poeta (2620)"
			      "Diophilus vel Diophila Poeta (2621)"
			      "Dorieus Poeta (2622)"
			      "Euanthes Epic. (2623)"
			      "Hermias Poeta (2624)"
			      "Herodicus Gramm. (2625)"
			      "Hipparchus Parodius (2626)"
			      "Damianus Scriptor De Opticis (2627)"
			      "Idaeus Epic. (2628)"
			      "Lobo Poeta (2630)"
			      "Menophilus Poeta (2631)"
			      "Comarius Alchem. (2632)"
			      "Niceratus Epic. (2633)"
			      "Pamphilus Poeta (2634)"
			      "Persinus Poeta (2635)"
			      "Pherenicus Epic. (2636)"
			      "Philo Poeta (2638)"
			      "Posidonius Epic. (2639)"
			      "Eusebius Phil. (2640)"
			      "Priscus Epic. (2641)"
			      "<Astrampsychus Magus> Onir. (2642)"
			      "Sminthes Astron. (2644)"
			      "Stratonicus Poeta (2645)"
			      "Fragmenta Adespota (SH) (2646)"
			      "Zenothemis Geogr. (2647)"
			      "Adespota Papyracea (SH) (2648)"
			      "Amyntas Epigr. (2649)"
			      "Arrianus Epic. (2650)"
			      "Artemidorus Eleg. (2651)"
			      "Diodorus Eleg. (2652)"
			      "Erycius Poeta (2653)"
			      "Physiologus (2654)"
			      "<Damigeron Magus> (2655)"
			      "Martyrium Ignatii (2657)"
			      "Testamentum Salomonis (2679)"
			      "Scythinus Epigr. (2680)"
			      "Diodorus Phil. (2681)"
			      "[Musaeus] Phil. (2691)"
			      "Ptolemaeus III Euergetes I <Epigr.> (2693)"
			      "Sostratus Poeta (2694)"
			      "Vitae Aristotelis (2695)"
			      "Theodorus Poeta (2696)"
			      "Timolaus Rhet. (2697)"
			      "Amphicrates Rhet. (2699)"
			      "Georgius Pisides Poeta (2701)"
			      "Michael Psellus Polyhist. (2702)"
			      "Anna Comnena Hist. (2703)"
			      "Theodorus Studites Scr. Eccl. et Theol. (2714)"
			      "Manuel Philes Poeta et Scr. Rerum Nat. (2718)"
			      "Theodorus Prodromus Poeta et Polyhist. (2721)"
			      "Ammonius Scr. Eccl. (2724)"
			      "Prorus Phil. (2729)"
			      "Evagrius Scholasticus Scr. Eccl. (2733)"
			      "Flavius Justinianus Imperator Theol. (2734)"
			      "Chronographiae Anonymae (2738)"
			      "Apophthegmata (2742)"
			      "Historia Monachorum In Aegypto (2744)"
			      "Gennadius I Scr. Eccl. (2762)"
			      "Eudocia Augusta Poeta (2766)"
			      "Callinicus Biogr. (2770)"
			      "Hesychius Scr. Eccl. (2797)"
			      "Pseudo-Dionysius Areopagita Scr. Eccl. et Theol. (2798)"
			      "Basilius Scr. Eccl. (2800)"
			      "Marcus Diaconus Scr. Eccl. (2806)"
			      "Antonius Hagiographus Scr. Eccl. (2807)"
			      "Joannes Gramm. et Theol. (2816)"
			      "Alexander Scr. Eccl. (2860)"
			      "Olympiodorus Diaconus Scr. Eccl. (2865)"
			      "Oecumenius Phil. et Rhet. (2866)"
			      "Joannes Malalas Chronogr. (2871)"
			      "Cyrillus Biogr. (2877)"
			      "Romanus Melodus Hymnographus (2881)"
			      "Maximus Confessor Theol. (2892)"
			      "Constitutiones Apostolorum (2894)"
			      "Minucianus Junior Rhet. (2903)"
			      "Nicolaus Rhet. et Soph. (2904)"
			      "Leontius Scr. Eccl. (2914)"
			      "Joannes Damascenus Scr. Eccl. et Theol. John of Damascus (2934)"
			      "Lachares Soph. (2937)"
			      "Gnomologium Vaticanum (2945)"
			      "Priscus Hist. et Rhet. (2946)"
			      "Acta Philippi (2948)"
			      "Acta Barnabae (2949)"
			      "Adamantius Theol. (2950)"
			      "Sextus Julius Africanus Hist. (2956)"
			      "Oracula Tiburtina (2960)"
			      "Petrus Scr. Eccl. et Theol. (2962)"
			      "Phileas Scr. Eccl. (2966)"
			      "Theodorus Heracleensis vel Theodorus Mopsuestenus Scr. Eccl. (2967)"
			      "Monimus Phil. (2968)"
			      "Demonax Phil. (2969)"
			      "Severus Phil. (2970)"
			      "Georgius Peccator Poeta (2971)"
			      "Anonymi De Terrae Motibus (2972)"
			      "Orus Gramm. (2995)"
			      "Prolegomena De Comoedia (3002)"
			      "Joannes Camaterus Astrol. et Astron. (3014)"
			      "Joannes Cameniates Hist. (3015)"
			      "Georgius Cedrenus Chronogr. (3018)"
			      "Joannes Cinnamus Gramm. et Hist. (3020)"
			      "Constantinus VII Porphyrogenitus Imperator Hist. (3023)"
			      "Joannes Doxapatres Rhet. (3027)"
			      "Joannes Galenus Gramm. (3039)"
			      "Josephus Genesius Hist. (3040)"
			      "Georgius Monachus Chronogr. (3043)"
			      "Georgius Syncellus Chronogr. (3045)"
			      "Michael Glycas Astrol. et Hist. (3047)"
			      "Georgius Monachus Continuatus (3051)"
			      "Joannes Scylitzes Hist. (3063)"
			      "Scylitzes Continuatus (3064)"
			      "Leo Diaconus Hist. (3069)"
			      "Symeon Logothetes Hist. (3070)"
			      "Constantinus Manasses Hist. et Poeta (3074)"
			      "Pseudo-Mauricius Tact. (3075)"
			      "Michael Attaliates Hist. (3079)"
			      "Nicephorus I Scr. Eccl., Hist. et Theol. (3086)"
			      "Nicephorus Bryennius Hist. (3088)"
			      "Nicetas Choniates Hist., Scr. Eccl. et Rhet. (3094)"
			      "Nicolaus I Mysticus Theol. et Epist. (3100)"
			      "Symeon Metaphrastes Biogr. et Hist. (3115)"
			      "Patria Constantinopoleos (3120)"
			      "Theodosius Diaconus Hist. et Poeta (3125)"
			      "Pseudo-Nonnus (3127)"
			      "Theognostus Gramm. (3128)"
			      "Theophylactus Simocatta Epist. et Hist. (3130)"
			      "Joannes Zonaras Gramm. et Hist. (3135)"
			      "Pseudo-Zonaras Lexicogr. (3136)"
			      "Laonicus Chalcocondyles Hist. (3139)"
			      "Joel Chronogr. (3140)"
			      "Georgius Acropolites Hist. (3141)"
			      "Georgius Pachymeres Hist. (3142)"
			      "Georgius Sphrantzes Hist. (3143)"
			      "Joannes Cananus Hist. (3144)"
			      "Joannes Anagnostes Hist. et Poeta (3145)"
			      "Ducas Hist. (3146)"
			      "Michael Critobulus Hist. (3147)"
			      "Joannes Protospatharius Gramm. (3155)"
			      "Anonymi Exegesis In Hesiodi Theogoniam (3156)"
			      "Theodorus Scutariota Hist. (3157)"
			      "Theodorus Epist. (3158)"
			      "Barlaam Math., Theol. et Epist. (3159)"
			      "Pseudo-Codinus Hist. (3168)"
			      "Joannes VI Cantacuzenus (3169)"
			      "Ephraem Hist. et Poeta (3170)"
			      "Joannes Theol. (3173)"
			      "Pseudo-Sphrantzes Hist. (3176)"
			      "Scriptor Incertus De Leone Armenio Hist. (3177)"
			      "Anonymi Lexeis Rhetoricae (3178)"
			      "Nicephorus II Phocas Imperator Tact. (3181)"
			      "Pseudo-Symeon Hist. (3182)"
			      "Anonymus De Scientia Politica Hist. (3185)"
			      "Anonymus Dialogus Cum Judaeis (3186)"
			      "Georgius Gramm. (3187)"
			      "Joannes Actuarius Med. (3188)"
			      "Aristaenetus Epist. (4000)"
			      "Aeneas Phil. et Rhet. (4001)"
			      "Marcianus Geogr. (4003)"
			      "Anonymus Discipulus Isidori Milesii Mech. (4005)"
			      "Simplicius Phil. (4013)"
			      "Priscianus Phil. (4014)"
			      "Joannes Philoponus Phil. (4015)"
			      "Ammonius Phil. (4016)"
			      "Syrianus Phil. (4017)"
			      "Asclepius Phil. (4018)"
			      "Olympiodorus Phil. (4019)"
			      "Elias Phil. (4020)"
			      "David Phil. (4021)"
			      "Agathias Scholasticus Epigr. et Hist. (4024)"
			      "Anonymi In Aristotelis Artem Rhetoricam Rhet. (4026)"
			      "Anonymi In Aristotelis Categorias Phil. (4027)"
			      "Stephanus Gramm. (4028)"
			      "Procopius Hist. (4029)"
			      "Sophonias Phil. (4030)"
			      "Eustratius Phil. (4031)"
			      "Anonymi In Aristotelis Librum Primum Analyticorum Posteriorum Commentarium (4032)"
			      "Anonymi In Aristotelis Ethica Nicomachea Phil. (4033)"
			      "Michael Phil. (4034)"
			      "Proclus Phil. (4036)"
			      "Anonymi Paradoxographi (4037)"
			      "Pamprepius Epic. (4038)"
			      "Paulus Silentiarius Poeta (4039)"
			      "Photius Lexicogr., Scr. Eccl. et Theol. (4040)"
			      "Theophanes Confessor Chronogr. (4046)"
			      "Cosmas Indicopleustes Geogr. (4061)"
			      "Damascius Phil. (4066)"
			      "Eutocius Math. (4072)"
			      "Marinus Phil. (4075)"
			      "Menander Protector Hist. (4076)"
			      "Geoponica (4080)"
			      "Colluthus Epic. (4081)"
			      "Musaeus Grammaticus Epic. (4082)"
			      "Eustathius Philol. et Scr. Eccl. (4083)"
			      "Zosimus Hist. (4084)"
			      "Hesychius Lexicogr. (4085)"
			      "[Agathodaemon] Alchem. (4086)"
			      "Anthemius Math. et Mech. (4088)"
			      "Theodoretus Scr. Eccl. et Theol. (4089)"
			      "Cyrillus Theol. (4090)"
			      "Callistratus Soph. (4091)"
			      "Georgius Choeroboscus Gramm. (4093)"
			      "Choricius Rhet. et Soph. (4094)"
			      "Dositheus Magister Gramm. (4096)"
			      "Etymologicum Genuinum (4097)"
			      "Etymologicum Gudianum (4098)"
			      "Etymologicum Magnum (4099)"
			      "Aphthonius Rhet. (4100)"
			      "Etymologicum Parvum (4101)"
			      "Catenae (Novum Testamentum) (4102)"
			      "Julianus Scr. Eccl. (4105)"
			      "Evagrius Scr. Eccl. (4110)"
			      "Theophilus Scr. Eccl. (4115)"
			      "Eustathius Scr. Eccl. et Theol. (4117)"
			      "Eusebius Scr. Eccl. (4124)"
			      "Theodorus Scr. Eccl. (4126)"
			      "Diodorus Scr. Eccl. (4134)"
			      "Theodorus Theol. (4135)"
			      "Ephraem Syrus Theol. (4138)"
			      "Severianus Scr. Eccl. (4139)"
			      "Nicephorus Gregoras Hist. (4145)"
			      "Florilegium Cyrillianum (4147)"
			      "Sophronius Gramm. (4149)"
			      "Anacreontea (4150)"
			      "Theophanes Continuatus (4153)"
			      "Joannes Rhet. (4157)"
			      "Vitae Arati Et Varia De Arato (4161)"
			      "Telegonia (4163)"
			      "Anonymi In Aristotelis Librum De Interpretatione Phil. (4165)"
			      "Vitae Aeschinis (4166)"
			      "Leontius Mech. (4167)"
			      "Vitae Pindari Et Varia De Pindaro (4170)"
			      "Anonymi In Oppiani Opera (4171)"
			      "Vitae Oppiani (4172)"
			      "Vitae Dionysii Periegetae (4173)"
			      "Paraphrases In Dionysium Periegetam (4174)"
			      "Commentaria In Dionysii Thracis Artem Grammaticam (4175)"
			      "Dionysius Soph. (4184)"
			      "Leo Magentinus Phil. (4187)"
			      "Anonymi In Aristotelis Sophisticos Elenchos Phil. (4193)"
			      "Joannes Chortasmenus Phil. (4201)"
			      "Anonymus De Philosophia Platonica Phil. (4227)"
			      "Joannes Rhet. (4235)"
			      "Trophonius Rhet. et Soph. (4236)"
			      "Joannes Argyropulus Gramm. (4237)"
			      "Athanasius Soph. (4238)"
			      "Severus Soph. (4239)"
			      "Cyrus Rhet. (4242)"
			      "Anonymus Manichaeus Biogr. (4282)"
			      "Lexica Syntactica (4286)"
			      "Etymologia Alphabeti (4287)"
			      "Lexicon αἱμωδεῖν (4288)"
			      "Lexica Segueriana (4289)"
			      "Lexicon Artis Grammaticae (4290)"
			      "Verba In Scripturis De Christo (4291)"
			      "Lexicon De Atticis Nominibus (4292)"
			      "Fragmentum Lexici Graeci (4293)"
			      "Lexicon Vindobonense (4294)"
			      "Lexicon Sabbaiticum (4300)"
			      "Lexicon Rhetoricum Cantabrigiense (4301)"
			      "Lexicon Patmense (4302)"
			      "Lexica In Opera Gregorii Nazianzeni (4303)"
			      "Glossae In Herodotum (4304)"
			      "Claudius Casilon Gramm. (4305)"
			      "Lexica Synonymica (4307)"
			      "Etymologicum Symeonis (4311)"
			      "Vita Sophoclis (4318)"
			      "Zosimus Alchem. (4319)"
			      "Eugenius Alchem. (4323)"
			      "Synesius Alchem. (4324)"
			      "[Hermes] Alchem. (4325)"
			      "Pappus Alchem. (4326)"
			      "Joannes Archiereus Alchem. (4327)"
			      "Philosophus Christianus Alchem. (4328)"
			      "Philosophus Anonymus Alchem. (4329)"
			      "Cosmas Hieromonachus Alchem. (4330)"
			      "Hierotheus Alchem. (4331)"
			      "Hierotheus Alchem. et Poeta (4332)"
			      "Nicephorus Blemmydes Alchem. (4333)"
			      "[Isis Prophetissa] Alchem. (4334)"
			      "Cleopatra Alchem. (4335)"
			      "Heliodorus Alchem. et Poeta (4337)"
			      "Theophrastus Alchem. et Poeta (4338)"
			      "Archelaus Alchem. et Poeta (4339)"
			      "Salmanas Alchem. (4340)"
			      "Menecrates Hist. (4344)"
			      "Menecrates Hist. (4345)"
			      "Menecrates Hist. (4346)"
			      "Andron Hist. (4347)"
			      "Apomasar Astrol. (4361)"
			      "Anonymi De Astrologia Dialogus Astrol. (4374)"
			      "Democles Hist. (4390)"
			      "Glaucus Hist. (4391)"
			      "Joannes Epiphaniensis Hist. (4392)"
			      "Nonnosus Hist. (4393)"
			      "Joannes Antiochenus Hist. (4394)"
			      "Menetor Hist. (4395)"
			      "Timagetus Hist. (4396)"
			      "Myronianus Hist. (4397)"
			      "Concilia Oecumenica (ACO) (5000)"
			      "Magica (5002)"
			      "Erotica Adespota (5003)"
			      "Epimerismi (5004)"
			      "Scholia In Aelium Aristidem (5008)"
			      "Scholia In Aeschinem (5009)"
			      "Scholia In Aeschylum (5010)"
			      "Scholia In Apollonium Rhodium (5012)"
			      "Scholia In Aratum (5013)"
			      "Scholia In Aristophanem (5014)"
			      "Scholia In Aristotelem (5015)"
			      "Scholia In Callimachum (5016)"
			      "Scholia In Demosthenem (5017)"
			      "Scholia In Dionysium Byzantium (5018)"
			      "Scholia In Dionysium Periegetam (5019)"
			      "Scholia In Diophantum (5021)"
			      "Scholia In Euclidem (5022)"
			      "Scholia In Euripidem (5023)"
			      "Anonymi In Hermogenem Rhet. (5024)"
			      "Scholia In Hesiodum (5025)"
			      "Scholia In Homerum (5026)"
			      "Scholia In Iamblichum Philosophum (5027)"
			      "Scholia In Isocratem (5028)"
			      "Scholia In Lucianum (5029)"
			      "Scholia In Lycophronem (5030)"
			      "Scholia In Nicandrum (5031)"
			      "Scholia In Oppianum (5032)"
			      "Scholia In Pausaniam (5033)"
			      "Scholia In Pindarum (5034)"
			      "Scholia In Platonem (5035)"
			      "Scholia In Sophoclem (5037)"
			      "Scholia In Theocritum (5038)"
			      "Scholia In Thucydidem (5039)"
			      "Scholia In Xenophontem (5040)"
			      "Anonymi In Aphthonium Rhet. (5045)"
			      "Scholia In Theonem Rhetorem (5046)"
			      "Scholia In Clementem Alexandrinum (5048)"
			      "Scholia in Maximum Confessorem (5052)"
			      "Anthologia Graeca AG (7000)"
			      "Doctrina Patrum (7051)"
			      "Anthologiae Graecae Appendix (7052)"
			      "Anonymus Lexicographus Lexicogr. (9003)"
			      "Anonymi In Aristotelis Librum Alterum Analyticorum Posteriorum Commentarium (9004)"
			      "Gregorius Paroemiogr. (9006)"
			      "Appendix Proverbiorum (9007)"
			      "Macarius Chrysocephalus Paroemiogr. (9008)"
			      "Michael Apostolius Paroemiogr. (9009)"
			      "Suda Suidas (9010)"
			      "Ignatius Biogr. et Poeta (9012)"
			      "Arsenius Paroemiogr. (9018)"
			      "Stephanus Phil. (9019)"
			      "Stephanus Gramm. (9020)"
			      "Stephanus Alchem. (9021)"
			      "Joannes Tzetzes Gramm. et Poeta (9022)"
			      "Thomas Magister Philol. (9023)") nil nil) -5 -1))



(defun diogenes-completing-author-latin ()
  "Reads the name of a Latin author from the minibuffer and returns the corresponding TLG number"
  (substring (completing-read "Author: " '(""
					   "Titus Annius Luscus (0002)"
					   "Appius Claudius Caecus (0004)"
					   "Aquilius, comoed. (0005)"
					   "Atilius (0007)"
					   "Marcus Iunius Brutus [iur.] (0010)"
					   "Caecilius Statius (0013)"
					   "Lucius Calpurnius Piso Frugi (0016)"
					   "Gaius Papirius Carbo (0019)"
					   "Marcus Porcius Cato Cato (0022)"
					   "Marcus Porcius Cato M.f.M.n. (0025)"
					   "Lucius Cincius Alimentus (0027)"
					   "Lucius Coelius Antipater (0028)"
					   "Cornelia, mater Gracchorum (0031)"
					   "Gaius Scribonius Curio avus (0034)"
					   "Gaius Scribonius Curio pater (0037)"
					   "Quintus Ennius (0043)"
					   "Cornelius Epicadus (0046)"
					   "Q. Fabius Maximus Servilianus (0058)"
					   "Fabius Pictor (0061)"
					   "Gaius Fannius (0064)"
					   "Favorinus (0067)"
					   "Gnaeus Gellius (0070)"
					   "Gaius Sempronius Gracchus (0073)"
					   "Gaius Cassius Hemina (0076)"
					   "Hostius (0079)"
					   "Decimus Iunius Silanus (0082)"
					   "Gaius Laelius Sapiens (0085)"
					   "M. Aemilius Lepidus Porcina (0088)"
					   "Licinius Imbrex (0091)"
					   "Lucius Livius Andronicus (0094)"
					   "Gaius Lucilius (0097)"
					   "Luscius Lanuvinus (0100)"
					   "Gnaeus Marcius vates (0103)"
					   "Gaius Memmius (0104)"
					   "Caecilius Metellus (0106)"
					   "Q. Caecilius Metellus Maced. (0109)"
					   "Gnaeus Naevius (0112)"
					   "Marcus Pacuvius (0116)"
					   "Papinius, epigram. (0117)"
					   "L. Aemilius L.f.M.n. Paulus (0118)"
					   "Titus Maccius Plautus (0119)"
					   "Aulus Postumius Albinus (0122)"
					   "Publius Mucius Scaevola (0125)"
					   "P. Cornel. Scipio Afr. ma. (0127)"
					   "P. Cornel. Scipio Aem. Afr. (0128)"
					   "P. Cornel. Scipio Nasica Ser. (0130)"
					   "Publius Terentius Afer Terence (0134)"
					   "Titinius (0137)"
					   "Gaius Titius (0140)"
					   "Trabea (0143)"
					   "Sextus Turpilius (0146)"
					   "Carmen Arvale (0149)"
					   "Sempronius Asellio (0300)"
					   "Gnaeus Domitius Ahenobarbus (0301)"
					   "Marcus Antonius (0302)"
					   "Aurelius Opillus (0303)"
					   "Carmen Devotionis (0306)"
					   "Carmen Evocationis (0309)"
					   "Fabius Dossennus (0312)"
					   "Marcus Iunius Gracchanus (0315)"
					   "Porcius Licinus (0321)"
					   "Saserna (0324)"
					   "L. Aelius Praeconinus Stilo (0327)"
					   "Volcacius Sedigitus (0330)"
					   "Lucius Accius (0400)"
					   "Aufustius (0401)"
					   "Valerius Aedituus (0402)"
					   "Lucius Afranius (0404)"
					   "Clodius Tuscus (0405)"
					   "Publius Alfenus Varus (0406)"
					   "Marcus Antonius triumvir (0408)"
					   "Quintus Cornificius (0409)"
					   "Aprissius (?) (0410)"
					   "Gaius Aquilius Gallus (0412)"
					   "Gavius Bassus (0413)"
					   "Lucius Arruntius (0414)"
					   "Lucius Ateius Praetextatus (0416)"
					   "Titus Quinctius Atta (0418)"
					   "Lucius Orbilius Pupillus (0419)"
					   "Publius Aufidius Namusa (0420)"
					   "Lucius Herennius Balbus (0423)"
					   "Publius Rutilius Lupus (0425)"
					   "Bellum Africum [Anonymous] (0426)"
					   "Bellum Alexandrinum [Anonymous] (0428)"
					   "Bellum Hispaniense [Anonymous] (0430)"
					   "Marcus Furius Bibaculus (0432)"
					   "Marcus Iunius Brutus [tyr.] (0436)"
					   "Aulus Caecina (0442)"
					   "Marcus Caelius Rufus (0444)"
					   "Gaius vel Lucius Caepasius (0445)"
					   "Quintus Servilius Caepio (0446)"
					   "Gaius Iulius Caesar Caesar (0448)"
					   "Lucius Iulius Caesar (0450)"
					   "Sinnius Capito (0451)"
					   "Gaius Iulius Caesar Strabo (0452)"
					   "Marcus Calidius (0454)"
					   "Gaius Calpurnius Piso (0455)"
					   "Gaius Licinius Macer Calvus (0456)"
					   "Publius Cannutius (0458)"
					   "Gaius Papirius Carbo Arvina (0460)"
					   "Aulus Cascellius (0466)"
					   "Lucius Cassius Longinus (0469)"
					   "Marcus Porcius Cato Uticensis (0470)"
					   "Gaius Valerius Catullus (0472)"
					   "Q. Lutatius Catulus iunior (0473)"
					   "Marcus Tullius Cicero Cicero Tully (0474)"
					   "Quintus Tullius Cicero (0478)"
					   "Lucius Cincius (0484)"
					   "Gaius Helvius Cinna (0486)"
					   "Publius Clodius Pulcher (0487)"
					   "Servius Clodius (0488)"
					   "Publius Cominius (0490)"
					   "Commentarii Augurum (0492)"
					   "Commentarii Consulares (0494)"
					   "Commentarius Anquisit. Sergii (0496)"
					   "Gaius Aurelius Cotta (0498)"
					   "Lucius Licinius Crassus (0500)"
					   "Aulus Cremutius Cordus (0502)"
					   "Publius Cornelius Dolabella (0510)"
					   "Marcus Duronius (0512)"
					   "Egnatius (0514)"
					   "Sextus (vel Spurius) Ennius (0515)"
					   "Gaius Erucius (0516)"
					   "Aulus Furius Antias (0518)"
					   "Gaius Aelius Gallus (0522)"
					   "Gaius Cornelius Gallus Gallus (0524)"
					   "Gaius Servilius Glaucia (0526)"
					   "Gannius (0527)"
					   "Granius Flaccus (0528)"
					   "Aulus Hirtius (0530)"
					   "Quintus Hortensius Hortalus (0532)"
					   "Gaius Iulius Hyginus (0533)"
					   "Iuventius, comoed. (0534)"
					   "Marcus Iuventius Laterensis (0535)"
					   "Decimus Laberius (0536)"
					   "Titus Labienus (0537)"
					   "Laevius (0538)"
					   "Tullius Laurea (0540)"
					   "Cn. Cornel. Lentulus Marcell. (0541)"
					   "Gaius Licinius Mucianus (0546)"
					   "Titus Lucretius Carus (0550)"
					   "Quintus Lutatius Catulus (0552)"
					   "Gaius Licinius Macer (0556)"
					   "Gaius Cilnius Maecenas (0558)"
					   "Helvius Mancia (0560)"
					   "Manilius, poet. (0562)"
					   "Manius Manilius (0564)"
					   "Gnaeus Matius (0568)"
					   "Gaius Memmius L. f. (0574)"
					   "M. Valerius Messalla Rufus (0576)"
					   "Q. Caecilius Metellus Numid. (0582)"
					   "Mimi Poetarum Incertorum (0584)"
					   "Mummius (0586)"
					   "Naevius, iunior (0587)"
					   "Cornelius Nepos (0588)"
					   "Publius Nigidius Figulus (0590)"
					   "Ninnius Crassus (0591)"
					   "Novius, comoed. (0592)"
					   "Lucius Novius (0594)"
					   "Numitorius (0596)"
					   "Gaius Oppius (0600)"
					   "Lucius Marcius Philippus (0606)"
					   "Q. Pompeius Q.f.A.n. Rufus (0614)"
					   "Q. Pompeius Q.f.Q.n. Rufus (0615)"
					   "Pompilius (0616)"
					   "Lucius Pomponius Bononiensis (0618)"
					   "Sextus Propertius (0620)"
					   "Publilius Syrus (0622)"
					   "Quintus Claudius Quadrigarius (0624)"
					   "Lucius Quinctius (0625)"
					   "Publius Rutilius Rufus (0628)"
					   "Sacra Argeorum (0630)"
					   "Gaius Sallustius Crispus (0631)"
					   "Santra (0634)"
					   "Publius Saturius (0635)"
					   "Quintus Mucius Scaevola (0636)"
					   "Q. Mucius Scaevola [pontifex] (0638)"
					   "Marcus Aemilius Scaurus (0640)"
					   "Sevius Nicanor (0642)"
					   "Sextilius Ena (0644)"
					   "Lucius Cornelius Sisenna (0646)"
					   "Staberius Eros (0648)"
					   "Sueius (0650)"
					   "Lucius Cornelius Sulla (0652)"
					   "Servius Sulpicius Rufus (0656)"
					   "Tabulae Censoriae (0658)"
					   "Albius Tibullus (0660)"
					   "Ticidas (0661)"
					   "Marcus Tullius Tiro (0662)"
					   "Gaius Trebatius Testa (0664)"
					   "Gnaeus Tremelius Scrofa (0668)"
					   "Quintus Aelius Tubero (0670)"
					   "Turranius Niger (0672)"
					   "Valerius, comoed. (0674)"
					   "Valerius Antias (0676)"
					   "Quintus Valerius Soranus (0678)"
					   "Gaius Valgius Rufus (0680)"
					   "Lucius Varius Rufus (0682)"
					   "Marcus Terentius Varro Varro (0684)"
					   "P. Terentius Varro Atacinus (0686)"
					   "Publius Vergilius Maro Virgil Vergil (0690)"
					   "Appendix Vergiliana (0692)"
					   "Volumnius (0694)"
					   "Arbonius Silo (0703)"
					   "Carmen de Bello Aegyptiaco (0706)"
					   "Domitius Marsus (0709)"
					   "Antonius Panurgus (0721)"
					   "Cloatius Verus (0724)"
					   "Cornificius Longus (0727)"
					   "Tarquitius Priscus (0730)"
					   "Albinovanus Pedo (0800)"
					   "Quintus Asconius Pedianus (0803)"
					   "Gaius Ateius Capito (0806)"
					   "Aufidius Bassus (0809)"
					   "Gaius Caesius Bassus (0812)"
					   "Bruttedius Niger (0815)"
					   "Bucolica Einsidlensia (0821)"
					   "Cn. Arulenus Caelius Sabinus (0824)"
					   "Caesellius Vindex (0827)"
					   "Titus Calpurnius Siculus (0830)"
					   "Aulus Cornelius Celsus (0836)"
					   "Gaius Clodius Licinus (0842)"
					   "L. Iunius Moderatus Columella (0845)"
					   "Cornelius Severus (0851)"
					   "Cornificius Gallus (0854)"
					   "Lucius Annaeus Cornutus (0857)"
					   "Quintus Curtius Rufus (0860)"
					   "Dorcatius (0863)"
					   "Fenestella (0866)"
					   "Marcus Verrius Flaccus (0869)"
					   "Cn. Cornel. Lentulus Gaetulicus (0875)"
					   "Gaius Asinius Gallus (0878)"
					   "Claudius Caesar Germanicus (0881)"
					   "Gracchus, trag. (0884)"
					   "Grattius (0887)"
					   "Homerus Latinus (0890)"
					   "Quintus Horatius Flaccus Horace (0893)"
					   "Hyginus Astronomus (0899)"
					   "Iulius Africanus (0902)"
					   "Marcus Antistius Labeo (0905)"
					   "Attius Labeo (0908)"
					   "Laus Pisonis (0911)"
					   "Titus Livius Livy (0914)"
					   "Marcus Annaeus Lucanus (0917)"
					   "Lucilius iunior (0920)"
					   "Aemilius Macer (0923)"
					   "Marcus Manilius Manilius (0926)"
					   "Pomponius Mela (0929)"
					   "M. Valerius Messalla Corvinus (0932)"
					   "Iulius Modestus (0935)"
					   "Iulius Montanus (0938)"
					   "Imperator Nero (0944)"
					   "Publius Ovidius Naso (0959)"
					   "Quintus Remmius Palaemon (0963)"
					   "Passienus Crispus (0966)"
					   "Aulus Persius Flaccus (0969)"
					   "Petronius (0972)"
					   "Phaedrus (0975)"
					   "Gaius Plinius Secundus Pliny (0978)"
					   "Gaius Asinius Pollio (0981)"
					   "Pompeius Trogus (0984)"
					   "Publius Pomponius Secundus (0987)"
					   "Precatio Omnium Herbarum (0990)"
					   "Precatio Terrae (0993)"
					   "Marcus Valerius Probus (0996)"
					   "Pupius (?) (1000)"
					   "Marcus Fabius Quintilianus (1002)"
					   "Rabirius (1005)"
					   "Scribonius Largus (1011)"
					   "Lucius Annaeus Seneca senior (1014)"
					   "Lucius Annaeus Seneca iunior (1017)"
					   "Publius Papinius Statius (1020)"
					   "Sulpicia, Caleni uxor (1023)"
					   "Turnus (1029)"
					   "Vagellius (1032)"
					   "Gaius Valerius Flaccus (1035)"
					   "Valerius Maximus (1038)"
					   "Pseudo-Varro (1041)"
					   "Velleius Paterculus (1044)"
					   "Veranius (1047)"
					   "Lucius Verginius Rufus (1050)"
					   "Vibius Crispus (1053)"
					   "Vitruvius (1056)"
					   "Calpurnius Flaccus (1100)"
					   "Priapea (1103)"
					   "Alfius Avitus (1203)"
					   "Lucius Ampelius (1206)"
					   "Annianus (1209)"
					   "Apuleius Madaurensis (1212)"
					   "Sentius Augurinus (1218)"
					   "C. Iul. Caes. Augustus Octavianus (1221)"
					   "Marcus Aurelius (1224)"
					   "Balbus, grom. (1227)"
					   "Flavius Caper (1229)"
					   "Didascaliae et Argum. in Plautum (1234)"
					   "Didascaliae et Per. in Terentium (1235)"
					   "Sextus Pompeius Festus (1236)"
					   "Annius Florus (1242)"
					   "Sextus Iulius Frontinus (1245)"
					   "Marcus Cornelius Fronto (1248)"
					   "Gaius, iur. Gaius (1251)"
					   "Aulus Gellius (1254)"
					   "Granius Licinianus (1257)"
					   "Hadrianus (1260)"
					   "Hyginus, myth. (1263)"
					   "Hyginus Gromaticus (1266)"
					   "Decimus Iunius Iuvenalis Juvenal (1276)"
					   "Laelius Felix (1279)"
					   "Lentulus, mimus (1282)"
					   "Lucius Volusius Maecianus (1285)"
					   "Marianus (1291)"
					   "Marcus Valerius Martialis (1294)"
					   "Marullus (1297)"
					   "Lucius Neratius Priscus (1306)"
					   "C. Plinius Caecilius Secundus Pliny (1318)"
					   "Sextus Pomponius (1321)"
					   "Sabidius (1327)"
					   "Scaevus Memor (1336)"
					   "Septimius Serenus (1339)"
					   "Siculus Flaccus (1342)"
					   "Silius Italicus (1345)"
					   "Gaius Suetonius Tranquillus (1348)"
					   "Cornelius Tacitus (1351)"
					   "Imp. Marcus Ulpius Traianus Trajan (1357)"
					   "Aemilius Asper (1363)"
					   "Quintus Terentius Scaurus (1370)"
					   "Velius Longus (1374)"
					   "Fragmenta Bobiensia (1377)"
					   "Philumenus medicus (1380)"
					   "Altercatio Hadr. et Epicteti (1500)"
					   "Anonymi Fragmenta de Iure Fisci (1506)"
					   "Pomponius Porphyrio (1512)"
					   "Quintus Serenus (Sammonicus) (1515)"
					   "Terentianus Maurus (1518)"
					   "Iulius Atherianus (1604)"
					   "Iulius Valerius (1672)"
					   "Gallus Antipater (1908)"
					   "Ablabius (2000)"
					   "Albinus, poet. (2002)"
					   "Caelius Apicius (2003)"
					   "Chalcidius (2028)"
					   "Sextus Paconianus (2097)"
					   "Publilius Optatianus Porfyrius (2123)"
					   "Zeno of Verona (2150)"
					   "Aemilius Sura (2300)"
					   "Q. Aurelius Memmius Symmachus (2301)"
					   "L. Aurel. Avianius Symmachus (2302)"
					   "Caelius Aurelianus (2305)"
					   "Scriptores Historiae Augustae (2331)"
					   "Anonymi de Differentiis [Fronto] (2335)"
					   "Maurus Servius Honoratus Servius (2349)"
					   "Hilarius Arelatensis (2434)"
					   "Parthenius Presbyter (2456)"
					   "Aurelius Augustinus (2468)"
					   "Iustinianus Justinian Digest (2806)"
					   "Argum. Aen. et Tetrast. (3211)"
					   "Paulus Quaestor (9221)"
					   "Titius, gram. (9254)"
					   "Anonymi Epici et Lyrici (9500)"
					   "Anonymi Comici et Tragici (9505)"
					   "Anonymi Grammatici (9510)"
					   "Vita Iuvenalis (9969)"
					   "Latin Canon (9999)") nil nil) -5 -1))

(defun diogenes-search-greek (query &optional author)
  "Searches for a phrase in the Greek TLG database using the diogenes command-line utility."
  (interactive (list
		(read-from-minibuffer "Enter search term: ")		
		(when (not (y-or-n-p "Search the whole TLG corpus? "))
		  (diogenes-completing-author-greek))))
  (if author
      (shell-command (format "diogenes-cli.pl -g -n %s '%s'" author query))
    (shell-command (format "diogenes-cli.pl -g '%s'" query))))

(defun diogenes-search-latin (query &optional author)
  "Searches for a phrase in the Greek TLG database using the diogenes command-line utility."
  (interactive (list
		(read-from-minibuffer "Enter search term: ")		
		(when (not (y-or-n-p "Search the whole PHI corpus? "))
		  (diogenes-completing-author-latin))))
  (if author
      (shell-command (format "diogenes-cli.pl -l -n %s '%s'" author query))
    (shell-command (format "diogenes-cli.pl -l '%s'" query))))

(defun diogenes-search-aristotle
    (query)
  "Searches for a phrase in Aristotle using the diogenes command-line utility."
  (interactive "sQuery: ")
  (shell-command (format "diogenes-cli.pl -g -n 0086 '%s'" query)))

(defun diogenes-search-greek-interactive
    (query)
  "Search interactvely the TLG database"
  (interactive "sQuery: ")
  (make-comint "diogenes-search" "diogenes-cli.pl" nil "-gF" query)
  (switch-to-buffer "*diogenes-search*"))

(defun diogenes-browse-greek
    (query)
  "Browse the TLG database"
  (interactive (list (diogenes-completing-author-greek)))
  (make-comint "diogenes-browse" "diogenes-cli.pl" nil "-bg" "-n" query)
  (switch-to-buffer "*diogenes-browse*"))

(defun diogenes-dump-greek
    (query)
  "Dumps the whole of a greek TLG text"
  (interactive (list (diogenes-completing-author-greek)))
  (make-comint "diogenes-browse" "diogenes-cli.pl" nil "-bg" "-c" "1000000" "-n" query)
  (switch-to-buffer "*diogenes-browse*"))

(defun diogenes-browse-latin
    (query)
  "Browse the PHI database"
  (interactive (list (diogenes-completing-author-latin)))
  (make-comint "diogenes-browse-latin" "diogenes-cli.pl" nil "-bl" "-n" query)
  (switch-to-buffer "*diogenes-browse-latin*"))

(defun diogenes-search-greek-wordlist
    (query)
  "Search the TLG using its wordlist."
  (interactive "sSearch TLG wordlist: ")
  (make-comint "diogenes-wordlist" "diogenes-cli.pl" nil "-w" query)
  (switch-to-buffer "*diogenes-wordlist*"))

(defun diogenes-search-greek-wordlist-all
    (query)
  "Search the TLG using its wordlist."
  (interactive "sSearch TLG wordlist (all): ")
  (shell-command (format "diogenes-cli.pl -wa %s" query)))

(defun diogenes-apostrophe (&optional start end)
  "Replace all greek apostrophes with the typographical correct ῾."
  (interactive "r")
    (save-excursion
      (save-restriction
	(when (use-region-p)
	  (progn (narrow-to-region start end)
		(goto-char (point-min))))
	(replace-regexp "\\([[:nonascii:]]+\\)['’]" "\\1᾿"))))
  
;; Problems with bracketed [] words
(defun diogenes-unhyphen-greek (&optional start end)
  "Delete hypenation in active region or until EOBP.
It works by adding the remainder of the word to the truncated
word and deleting it in the following line. Works on the rest of
the buffer starting at point, or on the active region."
  (interactive "r")
    (save-excursion
      (save-restriction
	(when (use-region-p)
	  (progn (narrow-to-region start end)
		(goto-char (point-min))))
	(while (re-search-forward "[^<]- ?$" (point-max) t)
	  (delete-horizontal-space)      
	  (delete-char -1)
	  (push-mark)
	  (forward-line)
	  (re-search-forward "[[:nonascii:]]+[.,·:;!?']?" (point-max) t)
	  (delete-horizontal-space)
	  (kill-word -1)
	  (exchange-point-and-mark)
	  (yank)
	  (pop-mark)
	  (setq kill-ring (cdr kill-ring))
	  (setq kill-ring-yank-pointer (cdr kill-ring-yank-pointer))))))


(defun diogenes-unhyphen (col &optional start end)
  "Delete hypenation in active region or until EOBP.
It works by adding the remainder of the word (starting at column
14, or column PREFIX) to the truncated word and deleting it in the following line.
Works on the rest of the buffer starting at point, or on the
active region."
  (interactive "p/nr")
  (when (= 1 col) (setq col 14))
    (save-excursion
      (save-restriction
	(when (use-region-p)
	  (progn (narrow-to-region start end)
		(goto-char (point-min))))
	(while (re-search-forward "[^<]- ?$" (point-max) t)
	  (delete-horizontal-space)      
	  (delete-char -1)
	  (push-mark)
	  (forward-line)
	  (move-to-column (or col 14))
	  (re-search-forward "[[:alpha:]]+[.,·:;!?']?" (point-max) t)
	  (delete-horizontal-space)
	  (kill-word -1)
	  (exchange-point-and-mark)
	  (yank)
	  (pop-mark)
	  (setq kill-ring (cdr kill-ring))
	  (setq kill-ring-yank-pointer (cdr kill-ring-yank-pointer))))))

;; For the future: Function to hide line numbers
(defun diogenes-delete-line-numbers ()
  "Delete line numbers, starting at point"
  (interactive)
  (save-excursion 
    (let ((start (progn
		   (unless
		       (re-search-backward
			"\([[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [[:digit:]][[:digit:]][[:digit:]]\)"
			nil t)
		     (re-search-forward 
			"\([[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [[:digit:]][[:digit:]][[:digit:]]\)"))
		   (re-search-forward "^$")
		   (point)))
	  (end (progn
		 ;; (goto-char (point-max))
		 (unless
		     (re-search-forward "diogenes-browse finished" nil t)
		   (goto-char (point-max)))
		 (re-search-backward "[Α‐ω]")
		 (beginning-of-line)
		 (forward-char 14)
		 (point))))
      (delete-rectangle start end))))

(defun diogenes-tidy-up-browser-output-greek ()
  "Tidy up the output of the Diogenes Browser.
Works on the rest of the buffer starting at point, or on the
active region."
  (interactive)
  ;; Delete the header
  (re-search-backward "^[[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [<\[]?[A-Z]")
  (save-excursion
    (save-restriction
      (narrow-to-region (point) (point-max))
      (re-search-forward "\([[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [[:digit:]][[:digit:]][[:digit:]]\)")
      (previous-line)		 
      ;; (re-search-forward "line\\?")
      ;; (next-line)
      (delete-backward-char (- (point) (point-min)))
      (delete-blank-lines)
      ;; Deleting the queries in the main text
      (while (re-search-forward "\\[more\\], \\[b\\]ack, \\[q\\]uit?" (point-max) t)
	(move-beginning-of-line nil)
	(previous-line)
	(let ((delete-start (point))
	      (delete-end (progn (next-line 6)
				 (point))))
	  (delete-region delete-start delete-end))
	(delete-blank-lines)
	(delete-blank-lines)
	;; Delete surplus line numbers
	(re-search-forward "[[:space:]]")
	(re-search-backward "[[:alnum:]]")
	(unless (or
		 (= ?0 (char-after))
		 (= ?1 (char-after))
		 (= ?5 (char-after)))
	  (let ((strlength (current-column)))
	    (delete-char 1)
	    (delete-backward-char strlength)
	    (insert-char 32 (+ 1 strlength)))))
      (goto-char (point-max))
      (insert-char ?% 70)
      (newline))))

(defun diogenes-tidy-up-browser-output-latin ()
  "Tidy up the output of the Diogenes Browser.
Works on the rest of the buffer starting at point, or on the
active region."
  (interactive)
  ;; Delete the header
  (re-search-backward "^[[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [<\[]?[A-Z]")
  (save-excursion
    (save-restriction
      (narrow-to-region (point) (point-max))
      (re-search-forward "\([[:digit:]][[:digit:]][[:digit:]][[:digit:]]: [[:digit:]][[:digit:]][[:digit:]]\)")
      (backward-paragraph)		 
      ;; (re-search-forward "line\\?")
      ;; (next-line)
      (delete-backward-char (- (point) (point-min)))
      (delete-blank-lines)
      ;; Deleting the queries in the main text
      (while (re-search-forward "\\[more\\], \\[b\\]ack, \\[q\\]uit?" (point-max) t)
	(move-beginning-of-line nil)
	(previous-line)
	(let ((delete-start (point))
	      (delete-end (progn (next-line 6)
				 (point))))
	  (delete-region delete-start delete-end))
	(delete-blank-lines)
	(delete-blank-lines)
	;; Delete surplus line numbers
	(re-search-forward "[[:space:]]")
	(re-search-backward "[[:alnum:]]")
	(unless (or
		 (= ?0 (char-after))
		 (= ?1 (char-after))
		 (= ?5 (char-after)))
	  (let ((strlength (current-column)))
	    (delete-char 1)
	    (delete-backward-char strlength)
	    (insert-char 32 (+ 1 strlength)))))
      (goto-char (point-max))
      (insert-char ?% 70)
      (newline))))

(defun diogenes-tidy-up-search-results ()
    "Post-processes search results of diogenes"
    (interactive)
    (save-excursion 
      (goto-char (point-min))   
      (diogenes-unhyphen-greek)
      (goto-char (point-min))
      (replace-regexp "->\\([[:alpha:]]*\\)<-\\([[:alpha:]]*\\)" "-> \\1\\2 -<")))

(defun diogenes-ol-to-ad (ol)
  "Converts Ol. to A.D."
  (interactive "nPlease enter the Olypiad: ")
  (let ((ad (+ -776 (* 4 (- ol 1)))))
    (if (< ad 0)
	(message "%d BC" (- 0 ad))
      (message "%d AD" (- ad 1)))))

(defun diogenes-ad-to-ol (ad)
  "Converts A.D. to Ol."
  (interactive "nPlease enter a year: ")
  (let ((ol)(yr))
    (when (< ad 0)
      (setq ol (+ ad 780))
      (setq yr (+ 1(% ol 4)))
      (setq ol (/ ol 4))
      (message "Ol. %d.%d" ol yr))
    (when (= ad 0)
      (error "There is no year 0!"))
    (when (> ad 0)
      (setq ol (+ ad 779))
      (setq yr (+ 1(% ol 4)))
      (setq ol (/ ol 4))
	(message "Ol. %d.%d" ol yr))))

(defun diogenes-browser-insert-line-numbers ()
  "Insert missing line numbers in diogenes browser output"
  (interactive)
  (while 
      (re-search-forward "^\\S-*[0-9]+")
    (let ((counter (string-to-number (thing-at-point 'word t))))
    (while
	(progn
	  (re-search-forward "^")
	  (string-match "\s" (char-to-string (char-after))))
      (insert (number-to-string (setq counter (1+ counter))))
      (forward-word)))))


(global-set-key (kbd "C-c d s") 'diogenes-search-greek)
(global-set-key (kbd "C-c d b") 'diogenes-browse-greek)
(global-set-key (kbd "C-c d w") 'diogenes-search-greek-wordlist)
(global-set-key (kbd "C-c d W") 'diogenes-search-greek-wordlist-all)
(global-set-key (kbd "C-c d u") 'diogenes-unhyphen-greek)
(global-set-key (kbd "C-c d a") 'diogenes-apostrophe)
(global-set-key (kbd "C-c d m") 'morpheus)
(global-set-key (kbd "C-c d l b") 'diogenes-browse-latin)
(global-set-key (kbd "C-c d l s") 'diogenes-search-latin)
(global-set-key (kbd "C-c d t s") 'diogenes-tidy-up-search-results)
(global-set-key (kbd "C-c d t b") 'diogenes-tidy-up-browser-output-greek)
(global-set-key (kbd "C-c d t l") 'diogenes-delete-line-numbers)

(provide 'diogenes)
